import React, { createContext, useContext, useState, useEffect } from 'react';

const LanguageContext = createContext();

export const translations = {
  en: {
    // App & Nav
    appName: 'PharmaVision AI',
    tagline: 'AI Medicine & Diagnostic Intelligence',
    menu: 'Menu',
    home: 'Home',
    assistant: 'AI Assistant',
    assistantSubtitle: 'Ask clinical questions, check drug interactions & get personalized guidance',
    scanner: 'Scanner',
    reportsRx: 'Reports & Rx',
    cabinet: 'My Cabinet',
    memoryCare: 'Memory Care',
    caregiver: 'Caregiver',
    voiceTherapy: 'Voice Therapy',
    history: 'History',
    profile: 'Profile',
    logout: 'Logout',
    signIn: 'Sign in',
    signUp: 'Sign up',
    register: 'Register',
    email: 'Email Address',
    password: 'Password',
    fullName: 'Full Name',
    alreadyAccount: 'Already have an account?',
    noAccount: "Don't have an account?",
    selectLanguage: 'Language',
    listenAudio: 'Listen (Audio)',
    speaking: 'Reading aloud...',

    // Dashboard
    goodMorning: 'Good morning',
    goodAfternoon: 'Good afternoon',
    goodEvening: 'Good evening',
    dashboardSubtitle: "Here's a summary of your medicine scanning and health activity.",
    totalScans: 'Total Scans',
    allTimeScans: 'All time medicine analyses',
    lastScanDate: 'Last Scan Date',
    noRecentScans: 'No recent scans',
    latestDrug: 'Latest Medication',
    verifiedAI: 'AI Vision verified',
    scanNewMedicine: 'Scan New Medicine',
    scanNewDesc: 'Point camera at any medicine packaging for instant dosage, indication & safety guidance',
    openScanner: 'Open Medicine Scanner',
    myCabinetTitle: 'My Medicine Cabinet',
    myCabinetDesc: 'View your scanned medicines automatically grouped into disease shelves',
    openCabinet: 'Open My Cabinet',
    reportsRxTitle: 'Reports & Prescription AI',
    reportsRxDesc: 'Digitize doctor prescriptions (1-0-1 schedule) or audit blood lab reports',
    openReports: 'Open Reports & Rx',
    recentScans: 'Recent Medicine Scans',
    viewAllHistory: 'View All History',
    noScansYet: 'No medicine scans yet. Click Scanner to analyze your first medication packaging!',
    openAssistant: 'Open AI Health Assistant',

    // Scanner
    positionMedicine: 'Position Medicine Label Here',
    captureAnalyze: 'Capture & Analyze Medicine',
    uploadFile: 'Upload File',
    switchCam: 'Switch Cam',
    retakeScan: 'Retake / Scan Another',
    analyzing: 'Analyzing Medicine Packaging with AI Vision...',
    analyzingDesc: 'Reading optical text, active ingredients, dosage markings, and safety details',
    flashcards: 'Flashcards',
    singleColumn: 'Single Column',
    showAllCards: 'Show All Cards',
    carouselView: 'Flashcard Carousel',
    previousCard: 'Previous Card',
    nextCard: 'Next Card',
    cardXofY: 'Card {x} of {y}',
    primaryUse: 'Primary Use & Indication',
    activeIngredients: 'Active Ingredients',
    dosageInstructions: 'Dosage Instructions',
    warnings: 'Critical Warnings & Precautions',
    sideEffects: 'Possible Side Effects',
    ncbiRecord: 'NCBI / NIH PubChem Record',
    aiPharmacist: 'AI Pharmacist Q&A Assistant',
    askPharmacist: 'Ask about this medicine...',
    askBtn: 'Ask',
    disclaimer: '* Disclaimer: PharmaVision AI is an assistive visual intelligence tool. Always verify medication details with a qualified healthcare professional or pharmacist.',

    // Reports & Prescriptions
    reportsHeaderTitle: 'Clinical Reports & Prescription Intelligence',
    reportsHeaderDesc: 'Extract medications, schedules, and clinical biomarker diagnostics from camera or PDF uploads',
    tabPrescription: 'Prescription OCR (1-0-1)',
    tabLabReport: 'Blood & Diagnostic Lab Report',
    tabDualAudit: 'Dual Rx + Pill Packaging Audit',

    // Cabinet
    cabinetHeaderTitle: 'My Medicine Cabinet',
    cabinetHeaderDesc: 'Intelligently grouped medications, custom alarms, and multi-disease shelves',
    allShelves: 'All Shelves',
    scheduleView: 'Daily Schedule',
    searchMedicine: 'Search medication or ingredient...',
    exportPdf: 'Export Clinical PDF',
    alarmSettings: 'Alarm Timings',
    morning: 'Morning',
    afternoon: 'Afternoon',
    night: 'Night',

    // Memory Care & Cognitive
    memoryCareTitle: 'Elderly Memory & Cognitive Care',
    memoryCareSubtitle: 'Daily interactive memory recall, personalized family reminiscence trivia, and adaptive neural stimulation',
    startMemoryMatch: 'Start Memory Match Game',
    dailyQuiz: 'Daily Orientation Quiz',
    cognitiveIndex: 'Cognitive Index',
    recallLatency: 'Recall Latency',
    caregiverTelemetry: 'Caregiver Telemetry',
    viewDashboard: 'View Dashboard →',
    familyVault: 'Family Memory Vault',
    addMemoryQuestion: 'Add Family Trivia Question',

    // Caregiver
    caregiverTitle: 'Caregiver & Family Telemetry',
    caregiverSubtitle: 'Real-time medication adherence, cognitive trend tracking, and missed routine alerts',
    cloudSynced: 'Cloud Synced',
    offlineMode: 'Offline Mode',
    adherenceRate: 'Adherence Rate',
    syncNow: 'Sync',
    primaryCaregiver: 'Primary Caregiver',
    routineTelemetry: 'Routine Telemetry',
    emergencyProtocol: 'Emergency Protocol',

    // Assistant
    connectedCabinet: '{count} Scanned Medicines in Cabinet',
    allergenShieldActive: 'Allergen Shield: {count} Saved Allergies',
    conditionsCount: '{count} Conditions Tracked',
    askAssistantPlaceholder: 'Ask anything about your medications, safety interactions, side effects, or meal rules…',
    quickPromptsTitle: 'Suggested Clinical Questions',
    promptInteractions: '🔍 Check interactions among all my cabinet medicines',
    promptSchedule: '⏰ What is my daily medicine routine and meal timing?',
    promptAllergies: '🛡️ Are all my current medications safe with my recorded allergies?',
    promptFoods: '🍏 Which foods, juices, or supplements should I avoid with my pills?',
    promptMissedDose: '❓ What should I do if I miss a scheduled dose?',
    clearChat: 'Clear Conversation',
    exportTranscript: 'Export Consultation',
    listening: 'Listening… speak now',
    voiceInput: 'Voice Input (Mic)',
    readAloud: 'Read Aloud',
    stopAudio: 'Stop Audio'
  },

  hi: {
    // App & Nav
    appName: 'फार्माविज़न एआई',
    tagline: 'एआई दवा और नैदानिक बुद्धिमत्ता',
    menu: 'मेनू',
    home: 'होम',
    assistant: 'एआई सहायक',
    assistantSubtitle: 'दवाओं की परस्पर क्रिया, दुष्प्रभाव और खुराक के बारे में पूछें',
    scanner: 'दवा स्कैनर',
    reportsRx: 'रिपोर्ट और पर्ची',
    cabinet: 'मेरी दवा अलमारी',
    memoryCare: 'स्मृति और मानसिक देखभाल',
    caregiver: 'देखभालकर्ता टेलीमेट्री',
    voiceTherapy: 'स्वर थेरेपी कक्ष',
    history: 'इतिहास',
    profile: 'प्रोफ़ाइल',
    logout: 'लॉगआउट',
    signIn: 'साइन इन करें',
    signUp: 'साइन अप करें',
    register: 'पंजीकरण करें',
    email: 'ईमेल पता',
    password: 'पासवर्ड',
    fullName: 'पूरा नाम',
    alreadyAccount: 'क्या आपके पास पहले से एक खाता है?',
    noAccount: 'खाता नहीं है?',
    selectLanguage: 'भाषा',
    listenAudio: 'ऑडियो सुनें',
    speaking: 'पढ़कर सुनाया जा रहा है...',

    // Dashboard
    goodMorning: 'शुभ प्रभात',
    goodAfternoon: 'शुभ दोपहर',
    goodEvening: 'शुभ संध्या',
    dashboardSubtitle: 'आपकी दवा स्कैनिंग और स्वास्थ्य गतिविधि का संपूर्ण सारांश।',
    totalScans: 'कुल स्कैन',
    allTimeScans: 'अब तक के सभी दवा विश्लेषण',
    lastScanDate: 'अंतिम स्कैन तिथि',
    noRecentScans: 'कोई हालिया स्कैन नहीं',
    latestDrug: 'नवीनतम दवा',
    verifiedAI: 'एआई विज़न सत्यापित',
    scanNewMedicine: 'नई दवा स्कैन करें',
    scanNewDesc: 'खुराक, उपयोग और सुरक्षा निर्देशों के लिए दवा के डिब्बे या पत्ते पर कैमरा रखें',
    openScanner: 'स्कैनर खोलें',
    myCabinetTitle: 'मेरी दवा अलमारी (कैबिनेट)',
    myCabinetDesc: 'अपनी सभी दवाओं को बीमारी के आधार पर वर्गीकृत अलमारियों में देखें',
    openCabinet: 'अलमारी खोलें',
    reportsRxTitle: 'रिपोर्ट्स और डॉक्टर की पर्ची',
    reportsRxDesc: 'डॉक्टर की पर्ची से दवाइयाँ निकालें (1-0-1 खुराक) या लैब ब्लड रिपोर्ट की जाँच करें',
    openReports: 'रिपोर्ट्स और पर्ची खोलें',
    recentScans: 'हाल की दवा स्कैन',
    viewAllHistory: 'पूरा इतिहास देखें',
    noScansYet: 'अभी तक कोई दवा स्कैन नहीं हुई है। अपनी पहली दवा का विश्लेषण करने के लिए स्कैनर पर क्लिक करें!',
    openAssistant: 'एआई स्वास्थ्य सहायक खोलें',

    // Scanner
    positionMedicine: 'दवा के लेबल को यहाँ फ्रेम में रखें',
    captureAnalyze: 'कैप्चर करें और विश्लेषण करें',
    uploadFile: 'फ़ाइल अपलोड करें',
    switchCam: 'कैमरा बदलें',
    retakeScan: 'पुनः स्कैन करें',
    analyzing: 'एआई विज़न द्वारा दवा पैकेजिंग का विश्लेषण किया जा रहा है...',
    analyzingDesc: 'ऑप्टिकल टेक्स्ट, सक्रिय घटक, खुराक के निशान और सुरक्षा विवरण पढ़े जा रहे हैं',
    flashcards: 'फ़्लैशकार्ड्स',
    singleColumn: 'एकल कॉलम',
    showAllCards: 'सभी कार्ड दिखाएं',
    carouselView: 'फ़्लैशकार्ड हिंडोला',
    previousCard: 'पिछला कार्ड',
    nextCard: 'अगला कार्ड',
    cardXofY: 'कार्ड {x} / {y}',
    primaryUse: 'प्राथमिक उपयोग और संकेत',
    activeIngredients: 'सक्रिय घटक',
    dosageInstructions: 'खुराक के निर्देश',
    warnings: 'महत्वपूर्ण चेतावनियां और सावधानियां',
    sideEffects: 'संभावित दुष्प्रभाव',
    ncbiRecord: 'एनसीबीआई / पबकेम रिकॉर्ड',
    aiPharmacist: 'एआई फार्मासिस्ट प्रश्नोत्तर सहायक',
    askPharmacist: 'इस दवा के बारे में पूछें...',
    askBtn: 'पूछें',
    disclaimer: '* अस्वीकरण: फार्माविज़न एआई एक सहायक उपकरण है। दवा लेने से पहले हमेशा डॉक्टर या फार्मासिस्ट से पुष्टि करें।',

    // Reports & Prescriptions
    reportsHeaderTitle: 'क्लिनिकल रिपोर्ट और पर्ची विश्लेषण',
    reportsHeaderDesc: 'कैमरे या पीडीएफ से दवाएं, शेड्यूल और ब्लड लैब मार्कर निकालें',
    tabPrescription: 'डॉक्टर की पर्ची (1-0-1)',
    tabLabReport: 'रक्त और नैदानिक लैब रिपोर्ट',
    tabDualAudit: 'दोहरी पर्ची + गोली सत्यापन',

    // Cabinet
    cabinetHeaderTitle: 'मेरी दवा अलमारी',
    cabinetHeaderDesc: 'बीमारी के अनुसार वर्गीकृत दवाएं, अलार्म और दिनचर्या',
    allShelves: 'सभी अलमारियां',
    scheduleView: 'दैनिक दिनचर्या',
    searchMedicine: 'दवा या घटक खोजें...',
    exportPdf: 'क्लिनिकल पीडीएफ निर्यात करें',
    alarmSettings: 'अलार्म समय',
    morning: 'सुबह',
    afternoon: 'दोपहर',
    night: 'रात',

    // Memory Care & Cognitive
    memoryCareTitle: 'स्मृति और संज्ञानात्मक देखभाल',
    memoryCareSubtitle: 'दैनिक इंटरैक्टिव स्मृति खेल, पारिवारिक प्रश्नोत्तरी और मानसिक स्वास्थ्य',
    startMemoryMatch: 'मेमोरी मैच खेलें',
    dailyQuiz: 'दैनिक ओरिएंटेशन क्विज',
    cognitiveIndex: 'संज्ञानात्मक स्कोर',
    recallLatency: 'याद करने का समय',
    caregiverTelemetry: 'देखभालकर्ता टेलीमेट्री',
    viewDashboard: 'डैशबोर्ड देखें →',
    familyVault: 'पारिवारिक मेमोरी वॉल्ट',
    addMemoryQuestion: 'नया पारिवारिक प्रश्न जोड़ें',

    // Caregiver
    caregiverTitle: 'देखभालकर्ता और परिवार टेलीमेट्री',
    caregiverSubtitle: 'वास्तविक समय में दवा सेवन, संज्ञानात्मक रुझान और छूटे हुए अलार्म',
    cloudSynced: 'क्लाउड सिंक हुआ',
    offlineMode: 'ऑफ़लाइन मोड',
    adherenceRate: 'दवा अनुपालन दर',
    syncNow: 'सिंक करें',
    primaryCaregiver: 'प्राथमिक देखभालकर्ता',
    routineTelemetry: 'रूटीन टेलीमेट्री',
    emergencyProtocol: 'आपातकालीन प्रोटोकॉल',

    // Assistant
    connectedCabinet: '{count} दवाइयाँ अलमारी में जुड़ी हैं',
    allergenShieldActive: 'एलर्जी शील्ड: {count} सहेजी गई एलर्जी',
    conditionsCount: '{count} स्वास्थ्य स्थितियाँ ट्रैक की गईं',
    askAssistantPlaceholder: 'अपनी दवाओं, परस्पर क्रियाओं, दुष्प्रभावों या भोजन के नियमों के बारे में पूछें...',
    quickPromptsTitle: 'सुझाए गए नैदानिक प्रश्न',
    promptInteractions: '🔍 मेरी सभी अलमारी दवाओं के बीच परस्पर क्रियाओं की जाँच करें',
    promptSchedule: '⏰ मेरी दैनिक दवा दिनचर्या और भोजन का समय क्या है?',
    promptAllergies: '🛡️ क्या मेरी सभी दवाएं मेरी दर्ज की गई एलर्जी के साथ सुरक्षित हैं?',
    promptFoods: '🍏 मुझे अपनी दवाओं के साथ किन खाद्य पदार्थों या रसों से बचना चाहिए?',
    promptMissedDose: '❓ यदि मैं एक निर्धारित खुराक भूल जाऊं तो क्या करूँ?',
    clearChat: 'बातचीत साफ़ करें',
    exportTranscript: 'परामर्श डाउनलोड करें',
    listening: 'सुन रहा हूँ... बोलिए',
    voiceInput: 'आवाज इनपुट (माइक)',
    readAloud: 'बोलकर सुनाएं',
    stopAudio: 'ऑडियो रोकें'
  },

  te: {
    // App & Nav
    appName: 'ఫార్మావిజన్ AI',
    tagline: 'AI ఔషధ & రోగనిర్ధారణ ఇంటెలిజెన్స్',
    menu: 'మెనూ',
    home: 'హోమ్',
    assistant: 'AI సహాయకుడు',
    assistantSubtitle: 'ఔషధ పరస్పర చర్యలు, దుష్ప్రభావాలు మరియు మోతాదు వివరాలను అడగండి',
    scanner: 'ఔషధ స్కానర్',
    reportsRx: 'నివేదికలు & ప్రిస్క్రిప్షన్',
    cabinet: 'నా మెడిసిన్ క్యాబినెట్',
    memoryCare: 'జ్ఞాపకశక్తి సంరక్షణ',
    caregiver: 'సంరక్షకుల సమాచారం',
    voiceTherapy: 'వాయిస్ థెరపీ రూమ్',
    history: 'చరిత్ర',
    profile: 'ప్రొఫైల్',
    logout: 'లాగ్అవుట్',
    signIn: 'సైన్ ఇన్',
    signUp: 'సైన్ అప్',
    register: 'నమోదు చేయండి',
    email: 'ఈమెయిల్ చిరునామా',
    password: 'పాస్వర్డ్',
    fullName: 'పూర్తి పేరు',
    alreadyAccount: 'ఇప్పటికే ఖాతా ఉందా?',
    noAccount: 'ఖాతా లేదా?',
    selectLanguage: 'భాష',
    listenAudio: 'వినండి (ఆడియో)',
    speaking: 'చదివి వినిపిస్తోంది...',

    // Dashboard
    goodMorning: 'శుభోదయం',
    goodAfternoon: 'శుభ మధ్యాహ్నం',
    goodEvening: 'శుభ సాయంత్రం',
    dashboardSubtitle: 'మీ మందుల స్కానింగ్ మరియు ఆరోగ్య సమాచారం యొక్క సారాంశం.',
    totalScans: 'మొత్తం స్కాన్‌లు',
    allTimeScans: 'ఇప్పటివరకు చేసిన అన్ని ఔషధ విశ్లేషణలు',
    lastScanDate: 'చివరి స్కాన్ తేదీ',
    noRecentScans: 'ఇటీవలి స్కాన్‌లు లేవు',
    latestDrug: 'తాజా మందు',
    verifiedAI: 'AI విజన్ ద్వారా ధృవీకరించబడింది',
    scanNewMedicine: 'కొత్త మందును స్కాన్ చేయండి',
    scanNewDesc: 'మోతాదు, సూచనలు & భద్రతా వివరాల కోసం కెమెరాను మందు ప్యాకింగ్‌పై ఉంచండి',
    openScanner: 'స్కానర్‌ని తెరవండి',
    myCabinetTitle: 'నా మెడిసిన్ క్యాబినెట్',
    myCabinetDesc: 'మీరు స్కాన్ చేసిన మందులను వ్యాధుల వారీగా వర్గీకరించిన షెల్ఫ్‌లలో చూడండి',
    openCabinet: 'క్యాబినెట్‌ను తెరవండి',
    reportsRxTitle: 'రిపోర్టులు & ప్రిస్క్రిప్షన్ AI',
    reportsRxDesc: 'డాక్టర్ ప్రిస్క్రిప్షన్ల నుండి మందులను లేదా ల్యాబ్ రక్త నివేదికలను విశ్లేషించండి',
    openReports: 'రిపోర్ట్‌లు & ప్రిస్క్రిప్షన్ తెరవండి',
    recentScans: 'ఇటీవలి ఔషధ స్కాన్‌లు',
    viewAllHistory: 'మొత్తం చరిత్రను చూడండి',
    noScansYet: 'ఇంకా ఎటువంటి ఔషధ స్కాన్‌లు లేవు. మీ మొదటి మందును విశ్లేషించడానికి స్కానర్‌పై క్లిక్ చేయండి!',
    openAssistant: 'AI ఆరోగ్య సహాయకుడిని తెరవండి',

    // Scanner
    positionMedicine: 'మందు లేబుల్‌ను ఇక్కడ సరిగ్గా ఉంచండి',
    captureAnalyze: 'క్యాప్చర్ చేసి విశ్లేషించండి',
    uploadFile: 'ఫైల్ అప్‌లోడ్ చేయండి',
    switchCam: 'కెమెరా మార్చండి',
    retakeScan: 'మళ్లీ స్కాన్ చేయండి',
    analyzing: 'AI విజన్ ద్వారా ఔషధ ప్యాకేజింగ్ విశ్లేషించబడుతోంది...',
    analyzingDesc: 'ఆప్టికల్ టెక్స్ట్, క్రియాశీల పదార్థాలు, మోతాదు గుర్తులు చదవబడుతున్నాయి',
    flashcards: 'ఫ్లాష్‌కార్డ్‌లు',
    singleColumn: 'సింగిల్ కాలమ్',
    showAllCards: 'అన్ని కార్డ్‌లను చూపించు',
    carouselView: 'కరోసెల్ వీక్షణ',
    previousCard: 'మునుపటి కార్డ్',
    nextCard: 'తదుపరి కార్డ్',
    cardXofY: 'కార్డ్ {x} / {y}',
    primaryUse: 'ప్రాథమిక ఉపయోగం & సూచన',
    activeIngredients: 'క్రియాశీల పదార్థాలు',
    dosageInstructions: 'మోతాదు సూచనలు',
    warnings: 'ముఖ్యమైన హెచ్చరికలు & జాగ్రత్తలు',
    sideEffects: 'సంభావ్య దుష్ప్రభావాలు',
    ncbiRecord: 'NCBI / PubChem రికార్డు',
    aiPharmacist: 'AI ఫార్మసిస్ట్ ప్రశ్నలు & సమాధానాలు',
    askPharmacist: 'ఈ మందు గురించి ఏదైనా అడగండి...',
    askBtn: 'అడగండి',
    disclaimer: '* గమనిక: ఫార్మావిజన్ AI ఒక సహాయక సాధనం మాత్రమే. మందు వాడే ముందు ఎల్లప్పుడూ వైద్యుడిని సంప్రదించండి.',

    // Reports & Prescriptions
    reportsHeaderTitle: 'క్లినికల్ రిపోర్ట్స్ & ప్రిస్క్రిప్షన్ విశ్లేషణ',
    reportsHeaderDesc: 'కెమెరా లేదా PDF నుండి మందుల షెడ్యూల్ మరియు ల్యాబ్ పరీక్షల వివరాలను పొందండి',
    tabPrescription: 'ప్రిస్క్రిప్షన్ OCR (1-0-1)',
    tabLabReport: 'రక్త & ల్యాబ్ నివేదిక',
    tabDualAudit: 'ప్రిస్క్రిప్షన్ + మాత్రల ధృవీకరణ',

    // Cabinet
    cabinetHeaderTitle: 'నా మెడిసిన్ క్యాబినెట్',
    cabinetHeaderDesc: 'వ్యాధి వారీగా మందుల వర్గీకరణ, అలారాలు మరియు షెడ్యూల్స్',
    allShelves: 'అన్ని షెల్ఫ్‌లు',
    scheduleView: 'రోజువారీ షెడ్యూల్',
    searchMedicine: 'మందు లేదా పదార్థాన్ని శోధించండి...',
    exportPdf: 'క్లినికల్ PDF డౌన్‌లోడ్',
    alarmSettings: 'అలారం సమయాలు',
    morning: 'ఉదయం',
    afternoon: 'మధ్యాహ్నం',
    night: 'రాత్రి',

    // Memory Care & Cognitive
    memoryCareTitle: 'జ్ఞాపకశక్తి & సంజ్ఞాన సంరక్షణ',
    memoryCareSubtitle: 'రోజువారీ జ్ఞాపకశక్తి ఆటలు, కుటుంబ జ్ఞాపకాల క్విజ్ మరియు మానసిక ఉల్లాసం',
    startMemoryMatch: 'మెమరీ మ్యాచ్ ఆట ఆడండి',
    dailyQuiz: 'రోజువారీ క్విజ్',
    cognitiveIndex: 'సంజ్ఞాన స్కోర్',
    recallLatency: 'గుర్తుకు తెచ్చుకునే సమయం',
    caregiverTelemetry: 'సంరక్షకుల సమాచారం',
    viewDashboard: 'డాష్‌బోర్డ్ చూడండి →',
    familyVault: 'కుటుంబ మెమరీ వాల్ట్',
    addMemoryQuestion: 'కుటుంబ ప్రశ్నను జోడించండి',

    // Caregiver
    caregiverTitle: 'సంరక్షకులు & కుటుంబ సమాచారం',
    caregiverSubtitle: 'మందుల వినియోగం, సంజ్ఞాన ధోరణులు మరియు అలారాల పర్యవేక్షణ',
    cloudSynced: 'క్లౌడ్‌తో సింక్ అయింది',
    offlineMode: 'ఆఫ్‌లైన్ మోడ్',
    adherenceRate: 'మందుల వినియోగ రేటు',
    syncNow: 'సింక్ చేయండి',
    primaryCaregiver: 'ప్రధాన సంరక్షకుడు',
    routineTelemetry: 'దినచర్య సమాచారం',
    emergencyProtocol: 'అత్యవసర ప్రోటోకాల్',

    // Assistant
    connectedCabinet: '{count} మందులు క్యాబినెట్‌లో ఉన్నాయి',
    allergenShieldActive: 'అలెర్జీ రక్షణ: {count} అలెర్జీలు నమోదయ్యాయి',
    conditionsCount: '{count} ఆరోగ్య సమస్యలు ట్రాక్ చేయబడ్డాయి',
    askAssistantPlaceholder: 'మీ మందులు, పరస్పర చర్యలు, దుష్ప్రభావాలు లేదా భోజన నియమాల గురించి అడగండి...',
    quickPromptsTitle: 'సూచించిన క్లినికల్ ప్రశ్నలు',
    promptInteractions: '🔍 నా క్యాబినెట్ మందులన్నింటి మధ్య పరస్పర చర్యలను తనిఖీ చేయండి',
    promptSchedule: '⏰ నా రోజువారీ మందుల షెడ్యూల్ & ఆహార సమయాలు ఏమిటి?',
    promptAllergies: '🛡️ నా నమోదు చేయబడిన అలెర్జీలతో నా ప్రస్తుత మందులన్నీ సురక్షితమేనా?',
    promptFoods: '🍏 నా మందులతో నేను ఏ ఆహారాలు, రసాలు లేదా సప్లిమెంట్లను నివారించాలి?',
    promptMissedDose: '❓ నేను షెడ్యూల్ చేసిన మోతాదును మిస్ అయితే ఏమి చేయాలి?',
    clearChat: 'చర్చను క్లియర్ చేయండి',
    exportTranscript: 'కన్సల్టేషన్ డౌన్‌లోడ్ చేయండి',
    listening: 'వింటున్నాను... మాట్లాడండి',
    voiceInput: 'వాయిస్ ఇన్‌పుట్ (మైక్)',
    readAloud: 'చదివి వినిపించండి',
    stopAudio: 'ఆడియో ఆపండి'
  },

  ta: {
    // Tamil
    appName: 'பார்மாவிஷன் AI',
    tagline: 'AI மருந்து மற்றும் மருத்துவ நுண்ணறிவு',
    menu: 'பட்டி',
    home: 'முகப்பு',
    assistant: 'AI உதவியாளர்',
    assistantSubtitle: 'மருந்து இடைவினைகள் மற்றும் பக்க விளைவுகள் பற்றி கேளுங்கள்',
    scanner: 'மருந்து ஸ்கேனர்',
    reportsRx: 'அறிக்கைகள் & மருந்துச்சீட்டு',
    cabinet: 'என் மருந்து பெட்டகம்',
    memoryCare: 'நினைவாற்றல் பாதுகாப்பு',
    caregiver: 'பராமரிப்பாளர் தகவல்',
    voiceTherapy: 'குரல் சிகிச்சை அறை',
    history: 'வரலாறு',
    profile: 'சுயவிவரம்',
    logout: 'வெளியேறு',
    signIn: 'உள்நுழைக',
    signUp: 'பதிவு செய்க',
    selectLanguage: 'மொழி',
    listenAudio: 'கேளுங்கள் (ஆடியோ)',
    speaking: 'படிக்கப்படுகிறது...',
    goodMorning: 'காலை வணக்கம்',
    goodAfternoon: 'மதிய வணக்கம்',
    goodEvening: 'மாலை வணக்கம்',
    dashboardSubtitle: 'உங்கள் மருந்து ஸ்கேனிங் மற்றும் சுகாதார செயல்பாட்டின் சுருக்கம்.',
    totalScans: 'மொத்த ஸ்கேன்கள்',
    scanNewMedicine: 'புதிய மருந்தை ஸ்கேன் செய்',
    scanNewDesc: 'மருந்தின் அளவு மற்றும் பாதுகாப்பு வழிகாட்டலுக்கு கேமராவை வையுங்கள்',
    openScanner: 'ஸ்கேனரைத் திற',
    myCabinetTitle: 'என் மருந்து பெட்டகம்',
    openCabinet: 'பெட்டகத்தைத் திற',
    reportsRxTitle: 'அறிக்கைகள் & மருந்துச்சீட்டு AI',
    openReports: 'அறிக்கைகளைத் திற',
    recentScans: 'சமீபத்திய ஸ்கேன்கள்',
    viewAllHistory: 'அனைத்து வரலாற்றையும் பார்',
    primaryUse: 'முக்கிய பயன்பாடு',
    activeIngredients: 'செயலில் உள்ள பொருட்கள்',
    dosageInstructions: 'மருந்தளவு வழிமுறைகள்',
    warnings: 'எச்சரிக்கைகள்',
    sideEffects: 'பக்க விளைவுகள்'
  },

  kn: {
    // Kannada
    appName: 'ಫಾರ್ಮಾವಿಷನ್ AI',
    tagline: 'AI ಔಷಧಿ ಮತ್ತು ರೋಗನಿರ್ಣಯ ಬುದ್ಧಿಮತ್ತೆ',
    menu: 'ಮೆನು',
    home: 'ಮುಖಪುಟ',
    assistant: 'AI ಸಹಾಯಕ',
    assistantSubtitle: 'ಔಷಧಿ ಪರಸ್ಪರ ಕ್ರಿಯೆಗಳು ಮತ್ತು ಅಡ್ಡಪರಿಣಾಮಗಳ ಬಗ್ಗೆ ಕೇಳಿ',
    scanner: 'ಔಷಧಿ ಸ್ಕ್ಯಾನರ್',
    reportsRx: 'ವರದಿಗಳು & ಪ್ರಿಸ್ಕ್ರಿಪ್ಷನ್',
    cabinet: 'ನನ್ನ ಔಷಧಿ ಕ್ಯಾಬಿನೆಟ್',
    memoryCare: 'ನೆನಪಿನ ಶಕ್ತಿ ಕಾಳಜಿ',
    caregiver: 'ಆರೈಕೆದಾರರ ಮಾಹಿತಿ',
    voiceTherapy: 'ಧ್ವನಿ ಚಿಕಿತ್ಸಾ ಕೊಠಡಿ',
    history: 'ಇತಿಹಾಸ',
    profile: 'ಪ್ರೊಫೈಲ್',
    logout: 'ಲಾಗ್‌ಔಟ್',
    signIn: 'ಸೈನ್ ಇನ್',
    signUp: 'ಸೈನ್ ಅಪ್',
    selectLanguage: 'ಭಾಷೆ',
    listenAudio: 'ಕೇಳಿ (ಆಡಿಯೋ)',
    speaking: 'ಓದಲಾಗುತ್ತಿದೆ...',
    goodMorning: 'ಶುಭೋದಯ',
    goodAfternoon: 'ಶುಭ ಮಧ್ಯಾಹ್ನ',
    goodEvening: 'ಶುಭ ಸಂಜೆ',
    dashboardSubtitle: 'ನಿಮ್ಮ ಔಷಧಿ ಸ್ಕ್ಯಾನಿಂಗ್ ಮತ್ತು ಆರೋಗ್ಯ ಚಟುವಟಿಕೆಯ ಸಾರಾಂಶ.',
    totalScans: 'ಒಟ್ಟು ಸ್ಕ್ಯಾನ್‌ಗಳು',
    scanNewMedicine: 'ಹೊಸ ಔಷಧಿ ಸ್ಕ್ಯಾನ್ ಮಾಡಿ',
    scanNewDesc: 'ಡೋಸೇಜ್ ಮತ್ತು ಸುರಕ್ಷತಾ ವಿವರಗಳಿಗಾಗಿ ಕ್ಯಾಮೆರಾವನ್ನು ಔಷಧಿ ಮೇಲೆ ಇರಿಸಿ',
    openScanner: 'ಸ್ಕ್ಯಾನರ್ ತೆರೆಯಿರಿ',
    myCabinetTitle: 'ನನ್ನ ಔಷಧಿ ಕ್ಯಾಬಿನೆಟ್',
    openCabinet: 'ಕ್ಯಾಬಿನೆಟ್ ತೆರೆಯಿರಿ',
    reportsRxTitle: 'ವರದಿಗಳು & ಪ್ರಿಸ್ಕ್ರಿಪ್ಷನ್ AI',
    openReports: 'ವರದಿಗಳನ್ನು ತೆರೆಯಿರಿ',
    recentScans: 'ಇತ್ತೀಚಿನ ಸ್ಕ್ಯಾನ್‌ಗಳು',
    viewAllHistory: 'ಎಲ್ಲಾ ಇತಿಹಾಸ ನೋಡಿ',
    primaryUse: 'ಪ್ರಾಥಮಿಕ ಬಳಕೆ',
    activeIngredients: 'ಸಕ್ರಿಯ ಪದಾರ್ಥಗಳು',
    dosageInstructions: 'ಡೋಸೇಜ್ ಸೂಚನೆಗಳು',
    warnings: 'ಎಚ್ಚರಿಕೆಗಳು',
    sideEffects: 'ಅಡ್ಡಪರಿಣಾಮಗಳು'
  },

  bn: {
    // Bengali
    appName: 'ফার্মাভিশন এআই',
    tagline: 'এআই ওষুধ এবং ডায়াগনস্টিক বুদ্ধিমত্তা',
    menu: 'মেনু',
    home: 'হোম',
    assistant: 'এআই সহকারী',
    assistantSubtitle: 'ওষুধের মিথস্ক্রিয়া এবং পার্শ্বপ্রতিক্রিয়া সম্পর্কে জিজ্ঞাসা করুন',
    scanner: 'ওষুধ স্ক্যানার',
    reportsRx: 'রিপোর্ট ও প্রেসক্রিপশন',
    cabinet: 'আমার মেডিসিন ক্যাবিনেট',
    memoryCare: 'স্মৃতি যত্ন ও মানসিক স্বাস্থ্য',
    caregiver: 'কেয়ারগিভার তথ্য',
    voiceTherapy: 'ভয়েস থেরাপি রুম',
    history: 'ইতিহাস',
    profile: 'প্রোফাইল',
    logout: 'লগআউট',
    signIn: 'সাইন ইন',
    signUp: 'সাইন আপ',
    selectLanguage: 'ভাষা',
    listenAudio: 'শুনুন (অডিও)',
    speaking: 'পড়া হচ্ছে...',
    goodMorning: 'সুপ্রভাত',
    goodAfternoon: 'শুভ দুপুর',
    goodEvening: 'শুভ সন্ধ্যা',
    dashboardSubtitle: 'আপনার ওষুধ স্ক্যানিং এবং স্বাস্থ্য কার্যকলাপের সারসংক্ষেপ।',
    totalScans: 'মোট স্ক্যান',
    scanNewMedicine: 'নতুন ওষুধ স্ক্যান করুন',
    scanNewDesc: 'ডোজ এবং সুরক্ষা নির্দেশনার জন্য ওষুধের প্যাকেটের দিকে ক্যামেরা ধরুন',
    openScanner: 'স্ক্যানার খুলুন',
    myCabinetTitle: 'আমার মেডিসিন ক্যাবিনেট',
    openCabinet: 'ক্যাবিনেট খুলুন',
    reportsRxTitle: 'রিপোর্ট ও প্রেসক্রিপশন এআই',
    openReports: 'রিপোর্ট খুলুন',
    recentScans: 'সাম্প্রতিক স্ক্যান',
    viewAllHistory: 'সমস্ত ইতিহাস দেখুন',
    primaryUse: 'প্রাথমিক ব্যবহার',
    activeIngredients: 'সক্রিয় উপাদান',
    dosageInstructions: 'ডোজ নির্দেশিকা',
    warnings: 'সতর্কতা',
    sideEffects: 'পার্শ্বপ্রতিক্রিয়া'
  },

  mr: {
    // Marathi
    appName: 'फार्माव्हिजन एआय',
    tagline: 'एआय औषध आणि निदान बुद्धिमत्ता',
    menu: 'मेनू',
    home: 'मुख्यपृष्ठ',
    assistant: 'एआय सहाय्यक',
    assistantSubtitle: 'औषधांचे दुष्परिणाम आणि परस्पर क्रियांविषयी विचारा',
    scanner: 'औषध स्कॅनर',
    reportsRx: 'अहवाल आणि प्रिस्क्रिप्शन',
    cabinet: 'माझे औषध कपाट',
    memoryCare: 'स्मृती आणि मानसिक काळजी',
    caregiver: 'काळजीवाहू माहिती',
    voiceTherapy: 'व्हॉइस थेरपी कक्ष',
    history: 'इतिहास',
    profile: 'प्रोफाइल',
    logout: 'लॉगआउट',
    signIn: 'साइन इन',
    signUp: 'साइन अप',
    selectLanguage: 'भाषा',
    listenAudio: 'ऐका (ऑडिओ)',
    speaking: 'वाचून दाखवत आहे...',
    goodMorning: 'शुभ प्रभात',
    goodAfternoon: 'शुभ दुपार',
    goodEvening: 'शुभ संध्याकाळ',
    dashboardSubtitle: 'तुमच्या औषध स्कॅनिंग आणि आरोग्याचा सारांश.',
    totalScans: 'एकूण स्कॅन्स',
    scanNewMedicine: 'नवीन औषध स्कॅन करा',
    scanNewDesc: 'डोस आणि सुरक्षिततेच्या माहितीसाठी कॅमेरा औषधावर धरा',
    openScanner: 'स्कॅनर उघडा',
    myCabinetTitle: 'माझे औषध कपाट',
    openCabinet: 'कपाट उघडा',
    reportsRxTitle: 'अहवाल आणि प्रिस्क्रिप्शन एआय',
    openReports: 'अहवाल उघडा',
    recentScans: 'अलीकडील स्कॅन्स',
    viewAllHistory: 'सर्व इतिहास पहा',
    primaryUse: 'प्राथमिक वापर',
    activeIngredients: 'सक्रिय घटक',
    dosageInstructions: 'डोस सूचना',
    warnings: 'महत्त्वाच्या सूचना',
    sideEffects: 'संभाव्य दुष्परिणाम'
  },

  es: {
    // Spanish
    appName: 'PharmaVision AI',
    tagline: 'Inteligencia Diagnóstica y de Medicamentos con IA',
    menu: 'Menú',
    home: 'Inicio',
    assistant: 'Asistente IA',
    assistantSubtitle: 'Consulta interacciones de medicamentos, dosis y precauciones',
    scanner: 'Escáner',
    reportsRx: 'Informes y Recetas',
    cabinet: 'Mi Botiquín',
    memoryCare: 'Cuidado de la Memoria',
    caregiver: 'Cuidador',
    voiceTherapy: 'Terapia de Voz',
    history: 'Historial',
    profile: 'Perfil',
    logout: 'Cerrar sesión',
    signIn: 'Iniciar sesión',
    signUp: 'Registrarse',
    selectLanguage: 'Idioma',
    listenAudio: 'Escuchar (Audio)',
    speaking: 'Leyendo en voz alta...',
    goodMorning: 'Buenos días',
    goodAfternoon: 'Buenas tardes',
    goodEvening: 'Buenas noches',
    dashboardSubtitle: 'Resumen de tus análisis de medicamentos y actividad médica.',
    totalScans: 'Escaneos Totales',
    scanNewMedicine: 'Escanear Medicamento',
    scanNewDesc: 'Apunta la cámara al envase del medicamento para ver dosis y seguridad',
    openScanner: 'Abrir Escáner',
    myCabinetTitle: 'Mi Botiquín',
    openCabinet: 'Abrir Botiquín',
    reportsRxTitle: 'Informes y Recetas con IA',
    openReports: 'Abrir Informes',
    recentScans: 'Escaneos Recientes',
    viewAllHistory: 'Ver Todo el Historial',
    primaryUse: 'Uso Principal e Indicación',
    activeIngredients: 'Ingredientes Activos',
    dosageInstructions: 'Instrucciones de Dosis',
    warnings: 'Advertencias y Precauciones',
    sideEffects: 'Posibles Efectos Secundarios'
  }
};

export const LanguageProvider = ({ children }) => {
  const [lang, setLang] = useState(() => {
    return localStorage.getItem('pharmavision_lang') || 'en';
  });

  useEffect(() => {
    // Keep document lang attribute in sync
    document.documentElement.lang = lang;
  }, [lang]);

  const changeLanguage = (newLang) => {
    if (translations[newLang]) {
      setLang(newLang);
      localStorage.setItem('pharmavision_lang', newLang);
      document.documentElement.lang = newLang;
      // Dispatch storage event so other tabs and components update seamlessly
      window.dispatchEvent(new Event('languageChange'));
    }
  };

  const t = (key, params = {}) => {
    let str = translations[lang]?.[key] || translations['en']?.[key] || key;
    if (typeof str === 'string') {
      Object.keys(params).forEach(p => {
        str = str.replace(new RegExp(`\\{${p}\\}`, 'g'), params[p]);
      });
    }
    return str;
  };

  return (
    <LanguageContext.Provider value={{ lang, changeLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
