import React, { createContext, useContext, useState } from 'react';

const LanguageContext = createContext();

export const translations = {
  en: {
    // App & Nav
    appName: 'PharmaVision AI',
    tagline: 'AI Medicine & Diagnostic Intelligence',
    home: 'Home',
    scanner: 'Scanner',
    reportsRx: 'Reports & Rx',
    cabinet: 'My Cabinet',
    history: 'History',
    profile: 'Profile',
    logout: 'Logout',
    signIn: 'Sign in',
    signUp: 'Sign up',
    register: 'Register',
    email: 'Email Address',
    password: 'Password',
    fullName: 'Full Name',
    alreadyAccount: 'Already have an account?',
    noAccount: "Don't have an account?",
    selectLanguage: 'Language',
    listenAudio: 'Listen (Audio)',
    speaking: 'Reading aloud...',

    // Dashboard
    goodMorning: 'Good morning',
    goodAfternoon: 'Good afternoon',
    goodEvening: 'Good evening',
    dashboardSubtitle: "Here's a summary of your medicine scanning and health activity.",
    totalScans: 'Total Scans',
    allTimeScans: 'All time medicine analyses',
    lastScanDate: 'Last Scan Date',
    noRecentScans: 'No recent scans',
    latestDrug: 'Latest Medication',
    verifiedAI: 'AI Vision verified',
    scanNewMedicine: 'Scan New Medicine',
    scanNewDesc: 'Point camera at any medicine packaging for instant dosage, indication & safety guidance',
    openScanner: 'Open Medicine Scanner',
    myCabinetTitle: 'My Medicine Cabinet',
    myCabinetDesc: 'View your scanned medicines automatically grouped into disease shelves',
    openCabinet: 'Open My Cabinet',
    reportsRxTitle: 'Reports & Prescription AI',
    reportsRxDesc: 'Digitize doctor prescriptions (1-0-1 schedule) or audit blood lab reports',
    openReports: 'Open Reports & Rx',
    recentScans: 'Recent Medicine Scans',
    viewAllHistory: 'View All History',
    noScansYet: 'No medicine scans yet. Click Scanner to analyze your first medication packaging!',

    // Scanner
    positionMedicine: 'Position Medicine Label Here',
    captureAnalyze: 'Capture & Analyze Medicine',
    uploadFile: 'Upload File',
    switchCam: 'Switch Cam',
    retakeScan: 'Retake / Scan Another',
    analyzing: 'Analyzing Medicine Packaging with AI Vision...',
    analyzingDesc: 'Reading optical text, active ingredients, dosage markings, and safety details',
    flashcards: 'Flashcards',
    singleColumn: 'Single Column',
    showAllCards: 'Show All Cards',
    carouselView: 'Flashcard Carousel',
    previousCard: 'Previous Card',
    nextCard: 'Next Card',
    cardXofY: 'Card {x} of {y}',
    primaryUse: 'Primary Use & Indication',
    activeIngredients: 'Active Ingredients',
    dosageInstructions: 'Dosage Instructions',
    warnings: 'Critical Warnings & Precautions',
    sideEffects: 'Possible Side Effects',
    ncbiRecord: 'NCBI / NIH PubChem Record',
    aiPharmacist: 'AI Pharmacist Q&A Assistant',
    askPharmacist: 'Ask about this medicine...',
    askBtn: 'Ask',
    disclaimer: '* Disclaimer: PharmaVision AI is an assistive visual intelligence tool. Always verify medication details with a qualified healthcare professional or pharmacist.',

    // Cabinet Page
    cabinetHeader: 'My Medicine Cabinet',
    cabinetSubtitle: 'All your medications automatically classified and organized into disease shelves for rapid access.',
    totalCabinetMeds: 'Total Cabinet Medications',
    activeDiseaseCats: 'Active Disease Shelves',
    orgStatus: 'Organization Status',
    allSorted: '100% Sorted',
    aiTaxonomy: 'AI Clinical Taxonomy Engine',
    searchPlaceholder: 'Search by medication name, active ingredient, or disease condition…',
    allDiseases: 'All Diseases',
    medicinesCount: '{count} Medicines',
    addedOn: 'Added on {date}',
    viewDetails: 'View Details',
    emptyCabinet: 'Your Medicine Cabinet is empty',
    emptyCabinetDesc: 'Scan a medication package or upload a doctor prescription to automatically organize your cabinet.',
    scanFirstMed: 'Scan First Medicine',

    // Reports & Rx Page
    reportsHeader: 'Reports & Prescription Intelligence',
    reportsSubtitle: 'Perform 360° dual consultation audits, digitize prescriptions with 1-0-1 dosage schedules, or analyze diagnostic blood reports.',
    dualAuditTab: '⚡ Dual Audit (Lab + Rx)',
    rxDigitizerTab: 'Prescription Digitizer',
    labReportTab: 'Lab Report Analyzer',
    uploadBothDocs: 'Upload Both Medical Documents',
    dualAuditDesc: 'Gemini AI will cross-verify whether prescribed drugs cover your abnormal lab biomarkers and catch organ-safety contraindications.',
    doc1Lab: 'Document 1: Blood / Lab Report (PDF / Image)',
    clickUploadLab: 'Click to Upload Lab Report',
    doc2Rx: "Document 2: Doctor's Prescription / Rx Note (PDF / Image)",
    clickUploadRx: 'Click to Upload Prescription',
    runDualAuditBtn: 'Run 360° Dual Consultation Audit',
    uploadRxTitle: "Upload Doctor Prescription (Rx)",
    rxUploadDesc: 'Supports Doctor Rx notes, clinic slips & e-prescriptions (PDF, PNG, JPG)',
    digitizeRxBtn: 'Digitize Prescription & Extract Medicines',
    uploadLabTitle: 'Upload Blood / Lab Report',
    labUploadDesc: 'Supports Blood Test, Lipid Panel, Metabolic reports up to 10MB',
    analyzeLabBtn: 'Analyze Report & Check Cabinet',

    // Flashcard Sections (Shared)
    reportSummary: 'Report Summary',
    labBiomarkers: 'Lab Biomarkers',
    cabinetCrossCheck: 'Cabinet Cross-Check',
    targetedExercises: 'Targeted Exercises',
    dietaryGuidance: 'Dietary Guidance',
    rxOverview: 'Rx Overview',
    prescribedDrugs: 'Prescribed Drugs',
    drugSafetyAlerts: 'Drug Safety & Alerts',
    clinicalIndications: 'Clinical Indications',
    doctorAdvice: 'Doctor Advice',
    auditScorecard: '360° Audit Scorecard',
    organSafety: 'Organ Safety Guardrails',
    treatmentMatrix: 'Treatment Alignment Matrix',
    unaddressedGaps: 'Unaddressed Gaps',
    lifestyleCoRx: 'Lifestyle Co-Prescription',

    // Timing & Schedule
    morning: 'Morning',
    afternoon: 'Afternoon',
    night: 'Night',
    duration: 'Duration',
    timing: 'Timing',
    saveToCabinet: 'Save ({count}) to Cabinet',
    selectedOf: 'Selected: {x} / {y}',

    // AI Health Assistant & Companion
    assistant: 'AI Health Assistant',
    assistantSubtitle: 'Personal clinical pharmacology companion with full context of your medicine cabinet & allergies.',
    activeMedsCount: '{count} Cabinet Meds',
    allergensCount: '{count} Allergens Shielded',
    conditionsCount: '{count} Conditions Tracked',
    askAssistantPlaceholder: 'Ask anything about your medications, safety interactions, side effects, or meal rules…',
    quickPromptsTitle: 'Suggested Clinical Questions',
    promptInteractions: '🔍 Check interactions among all my cabinet medicines',
    promptSchedule: '⏰ What is my daily medicine routine and meal timing?',
    promptAllergies: '🛡️ Are all my current medications safe with my recorded allergies?',
    promptFoods: '🍏 Which foods, juices, or supplements should I avoid with my pills?',
    promptMissedDose: '❓ What should I do if I miss a scheduled dose?',
    clearChat: 'Clear Conversation',
    exportTranscript: 'Export Consultation',
    listening: 'Listening… speak now',
    voiceInput: 'Voice Input (Mic)',
    readAloud: 'Read Aloud',
    stopAudio: 'Stop Audio',
    openAssistant: 'Open AI Health Assistant'
  },

  hi: {
    // App & Nav
    appName: 'फार्माविज़न एआई',
    tagline: 'एआई दवा और नैदानिक बुद्धिमत्ता',
    home: 'होम',
    scanner: 'दवा स्कैनर',
    reportsRx: 'रिपोर्ट और पर्ची',
    cabinet: 'मेरी दवा अलमारी',
    history: 'इतिहास',
    profile: 'प्रोफ़ाइल',
    logout: 'लॉगआउट',
    signIn: 'साइन इन करें',
    signUp: 'साइन अप करें',
    register: 'पंजीकरण करें',
    email: 'ईमेल पता',
    password: 'पासवर्ड',
    fullName: 'पूरा नाम',
    alreadyAccount: 'क्या आपके पास पहले से एक खाता है?',
    noAccount: 'खाता नहीं है?',
    selectLanguage: 'भाषा',
    listenAudio: 'ऑडियो सुनें',
    speaking: 'पढ़कर सुनाया जा रहा है...',

    // Dashboard
    goodMorning: 'शुभ प्रभात',
    goodAfternoon: 'शुभ दोपहर',
    goodEvening: 'शुभ संध्या',
    dashboardSubtitle: 'आपकी दवा स्कैनिंग और स्वास्थ्य गतिविधि का संपूर्ण सारांश।',
    totalScans: 'कुल स्कैन',
    allTimeScans: 'अब तक के सभी दवा विश्लेषण',
    lastScanDate: 'अंतिम स्कैन तिथि',
    noRecentScans: 'कोई हालिया स्कैन नहीं',
    latestDrug: 'नवीनतम दवा',
    verifiedAI: 'एआई विज़न सत्यापित',
    scanNewMedicine: 'नई दवा स्कैन करें',
    scanNewDesc: 'खुराक, उपयोग और सुरक्षा निर्देशों के लिए दवा के डिब्बे या पत्ते पर कैमरा रखें',
    openScanner: 'स्कैनर खोलें',
    myCabinetTitle: 'मेरी दवा अलमारी (कैबिनेट)',
    myCabinetDesc: 'अपनी सभी दवाओं को बीमारी के आधार पर वर्गीकृत अलमारियों में देखें',
    openCabinet: 'अलमारी खोलें',
    reportsRxTitle: 'रिपोर्ट्स और डॉक्टर की पर्ची',
    reportsRxDesc: 'डॉक्टर की पर्ची से दवाइयाँ निकालें (1-0-1 खुराक) या लैब ब्लड रिपोर्ट की जाँच करें',
    openReports: 'रिपोर्ट्स और पर्ची खोलें',
    recentScans: 'हाल की दवा स्कैन',
    viewAllHistory: 'पूरा इतिहास देखें',
    noScansYet: 'अभी तक कोई दवा स्कैन नहीं हुई है। अपनी पहली दवा का विश्लेषण करने के लिए स्कैनर पर क्लिक करें!',

    // Scanner
    positionMedicine: 'दवा के लेबल को यहाँ फ्रेम में रखें',
    captureAnalyze: 'कैप्चर करें और विश्लेषण करें',
    uploadFile: 'फ़ाइल अपलोड करें',
    switchCam: 'कैमरा बदलें',
    retakeScan: 'पुनः स्कैन करें',
    analyzing: 'एआई विज़न द्वारा दवा पैकेजिंग का विश्लेषण किया जा रहा है...',
    analyzingDesc: 'ऑप्टिकल टेक्स्ट, सक्रिय सामग्री, खुराक और सुरक्षा विवरण पढ़ा जा रहा है',
    flashcards: 'फ़्लैशकार्ड',
    singleColumn: 'एकल सूची',
    showAllCards: 'सभी कार्ड दिखाएं',
    carouselView: 'फ़्लैशकार्ड हिंडोला',
    previousCard: 'पिछला कार्ड',
    nextCard: 'अगला कार्ड',
    cardXofY: 'कार्ड {x} का {y}',
    primaryUse: 'प्राथमिक उपयोग और संकेत',
    activeIngredients: 'सक्रिय सामग्रियां',
    dosageInstructions: 'खुराक के निर्देश',
    warnings: 'गंभीर चेतावनियां और सावधानियां',
    sideEffects: 'संभावित दुष्प्रभाव',
    ncbiRecord: 'एनसीबीआई / एनआईएच पबकेम रिकॉर्ड',
    aiPharmacist: 'एआई फार्मासिस्ट प्रश्नोत्तर सहायक',
    askPharmacist: 'इस दवा के बारे में पूछें...',
    askBtn: 'पूछें',
    disclaimer: '* अस्वीकरण: फार्माविज़न एआई एक सहायक दृश्य बुद्धिमत्ता उपकरण है। हमेशा एक योग्य डॉक्टर या फार्मासिस्ट से दवा विवरण की पुष्टि करें।',

    // Cabinet Page
    cabinetHeader: 'मेरी दवा अलमारी (कैबिनेट)',
    cabinetSubtitle: 'आपकी सभी दवाएं बीमारियों के आधार पर स्वतः वर्गीकृत होकर आपकी डिजिटल अलमारी में व्यवस्थित हैं।',
    totalCabinetMeds: 'अलमारी में कुल दवाइयाँ',
    activeDiseaseCats: 'सक्रिय बीमारी अलमारियाँ',
    orgStatus: 'वर्गीकरण स्थिति',
    allSorted: '100% क्रमबद्ध',
    aiTaxonomy: 'एआई क्लीनिकल टैक्सोनॉमी इंजन',
    searchPlaceholder: 'दवा का नाम, घटक या बीमारी खोजें…',
    allDiseases: 'सभी बीमारियाँ',
    medicinesCount: '{count} दवाइयाँ',
    addedOn: '{date} को जोड़ा गया',
    viewDetails: 'विवरण देखें',
    emptyCabinet: 'आपकी दवा अलमारी खाली है',
    emptyCabinetDesc: 'अलमारी में जोड़ने के लिए दवा का डिब्बा स्कैन करें या डॉक्टर का पर्चा अपलोड करें।',
    scanFirstMed: 'पहली दवा स्कैन करें',

    // Reports & Rx Page
    reportsHeader: 'लैब रिपोर्ट और डॉक्टर पर्ची इंटेलिजेंस',
    reportsSubtitle: '360° ड्यूल परामर्श ऑडिट करें, डॉक्टर की पर्ची से 1-0-1 खुराक निकालें, या ब्लड टेस्ट का विश्लेषण करें।',
    dualAuditTab: '⚡ ड्यूल ऑडिट (लैब + पर्ची)',
    rxDigitizerTab: 'पर्ची डिजिटाइज़र',
    labReportTab: 'लैब रिपोर्ट विश्लेषक',
    uploadBothDocs: 'दोनों मेडिकल दस्तावेज़ अपलोड करें',
    dualAuditDesc: 'एआई यह जाँचेगा कि लिखी गई दवाइयाँ आपकी असामान्य लैब रिपोर्ट को ठीक करती हैं या नहीं और अंगों की सुरक्षा जाँचेगा।',
    doc1Lab: 'दस्तावेज़ 1: ब्लड / लैब रिपोर्ट (PDF / फोटो)',
    clickUploadLab: 'लैब रिपोर्ट अपलोड करने के लिए क्लिक करें',
    doc2Rx: 'दस्तावेज़ 2: डॉक्टर की पर्ची / Rx (PDF / फोटो)',
    clickUploadRx: 'डॉक्टर की पर्ची अपलोड करने के लिए क्लिक करें',
    runDualAuditBtn: '360° ड्यूल परामर्श ऑडिट शुरू करें',
    uploadRxTitle: 'डॉक्टर की पर्ची (Rx) अपलोड करें',
    rxUploadDesc: 'हस्तलिखित पर्ची, क्लीनिक रसीद और ई-पर्ची (PDF, PNG, JPG) समर्थित',
    digitizeRxBtn: 'पर्ची से दवाइयाँ और खुराक निकालें',
    uploadLabTitle: 'ब्लड / लैब रिपोर्ट अपलोड करें',
    labUploadDesc: 'ब्लड टेस्ट, लिपिड प्रोफाइल, मेटाबोलिक रिपोर्ट (10MB तक)',
    analyzeLabBtn: 'रिपोर्ट का विश्लेषण करें और अलमारी से मिलाएँ',

    // Flashcard Sections (Shared)
    reportSummary: 'रिपोर्ट सारांश',
    labBiomarkers: 'लैब बायोमार्कर',
    cabinetCrossCheck: 'अलमारी से मिलान',
    targetedExercises: 'लक्षित व्यायाम',
    dietaryGuidance: 'आहार मार्गदर्शन',
    rxOverview: 'पर्ची सारांश',
    prescribedDrugs: 'निर्धारित दवाइयाँ',
    drugSafetyAlerts: 'दवा सुरक्षा व इंटरैक्शन',
    clinicalIndications: 'चिकित्सीय उपयोग',
    doctorAdvice: 'डॉक्टर की सलाह',
    auditScorecard: '360° ऑडिट स्कोरकार्ड',
    organSafety: 'अंग सुरक्षा चेतावनियाँ',
    treatmentMatrix: 'इलाज मिलान मैट्रिक्स',
    unaddressedGaps: 'छूटे हुए लैब निष्कर्ष',
    lifestyleCoRx: 'जीवनशैली व आहार सलाह',

    // Timing & Schedule
    morning: 'सुबह',
    afternoon: 'दोपहर',
    night: 'रात',
    duration: 'अवधि',
    timing: 'समय',
    saveToCabinet: 'अलमारी में सहेजें ({count})',
    selectedOf: 'चयनित: {x} / {y}',

    // AI Health Assistant & Companion
    assistant: 'एआई स्वास्थ्य सहायक',
    assistantSubtitle: 'आपकी दवा अलमारी और एलर्जी के पूर्ण संदर्भ के साथ व्यक्तिगत स्वास्थ्य साथी।',
    activeMedsCount: '{count} दवाएं सक्रिय',
    allergensCount: '{count} एलर्जी सुरक्षित',
    conditionsCount: '{count} स्थितियां ट्रैक की गईं',
    askAssistantPlaceholder: 'अपनी दवाओं, इंटरैक्शन, साइड इफेक्ट्स या भोजन के नियमों के बारे में कुछ भी पूछें…',
    quickPromptsTitle: 'सुझाए गए नैदानिक प्रश्न',
    promptInteractions: '🔍 मेरी सभी दवाओं के बीच संभावित परस्पर क्रिया (interactions) जांचें',
    promptSchedule: '⏰ मेरा दैनिक दवा शेड्यूल और भोजन के नियम क्या हैं?',
    promptAllergies: '🛡️ क्या मेरी सभी दवाएं मेरी दर्ज की गई एलर्जी के साथ सुरक्षित हैं?',
    promptFoods: '🍏 मुझे अपनी दवाओं के साथ किन खाद्य पदार्थों या रसों से बचना चाहिए?',
    promptMissedDose: '❓ यदि मेरी कोई खुराक छूट जाए तो मुझे क्या करना चाहिए?',
    clearChat: 'बातचीत साफ़ करें',
    exportTranscript: 'परामर्श डाउनलोड करें',
    listening: 'सुन रहा हूँ... बोलिए',
    voiceInput: 'आवाज़ से पूछें (माइक)',
    readAloud: 'पढ़कर सुनाएं',
    stopAudio: 'ऑडियो रोकें',
    openAssistant: 'एआई स्वास्थ्य सहायक खोलें'
  },

  te: {
    // App & Nav
    appName: 'ఫార్మావిజన్ AI',
    tagline: 'AI మందులు మరియు డయాగ్నస్టిక్ ఇంటెలిజెన్స్',
    home: 'హోమ్',
    scanner: 'మందుల స్కానర్',
    reportsRx: 'రిపోర్ట్‌లు & ప్రిస్క్రిప్షన్',
    cabinet: 'నా మెడిసిన్ క్యాబినెట్',
    history: 'చరిత్ర',
    profile: 'ప్రొఫైల్',
    logout: 'లాగ్ అవుట్',
    signIn: 'సైన్ ఇన్',
    signUp: 'సైన్ అప్',
    register: 'రిజిస్టర్',
    email: 'ఈమెయిల్ చిరునామా',
    password: 'పాస్‌వర్డ్',
    fullName: 'పూర్తి పేరు',
    alreadyAccount: 'ఇప్పటికే ఖాతా ఉందా?',
    noAccount: 'ఖాతా లేదా?',
    selectLanguage: 'భాష',
    listenAudio: 'ఆడియో వినండి',
    speaking: 'చదివి వినిపిస్తోంది...',

    // Dashboard
    goodMorning: 'శుభోదయం',
    goodAfternoon: 'శుభ మధ్యాహ్నం',
    goodEvening: 'శుభ సాయంత్రం',
    dashboardSubtitle: 'మీ మందుల స్కానింగ్ మరియు ఆరోగ్య సమాచార సారాంశం.',
    totalScans: 'మొత్తం స్కాన్లు',
    allTimeScans: 'ఇప్పటివరకు చేసిన మందుల విశ్లేషణలు',
    lastScanDate: 'చివరి స్కాన్ తేదీ',
    noRecentScans: 'ఇటీవలి స్కాన్లు లేవు',
    latestDrug: 'తాజా మందు',
    verifiedAI: 'AI విజన్ ధృవీకరించబడింది',
    scanNewMedicine: 'కొత్త మందును స్కాన్ చేయండి',
    scanNewDesc: 'మోతాదు, ఉపయోగాలు మరియు రక్షణ వివరాల కోసం మందుల ప్యాకెట్‌ను కెమెరాలో చూపించండి',
    openScanner: 'స్కానర్ తెరవండి',
    myCabinetTitle: 'నా మెడిసిన్ క్యాబినెట్',
    myCabinetDesc: 'మీ మందులన్నీ వ్యాధుల వారీగా క్రమబద్ధీకరించబడిన అరల్లో చూడండి',
    openCabinet: 'క్యాబినెట్ తెరవండి',
    reportsRxTitle: 'రిపోర్ట్‌లు & డాక్టర్ ప్రిస్క్రిప్షన్ AI',
    reportsRxDesc: 'డాక్టర్ చీటీ నుండి మందులు తీయండి (1-0-1 మోతాదు) లేదా బ్లడ్ రిపోర్ట్‌ను విశ్లేషించండి',
    openReports: 'రిపోర్ట్‌లు & చీటీ తెరవండి',
    recentScans: 'ఇటీవలి మందుల స్కాన్లు',
    viewAllHistory: 'మొత్తం చరిత్ర చూడండి',
    noScansYet: 'ఇంకా మందుల స్కాన్‌లు లేవు. మీ మొదటి మందు ప్యాకేజీని విశ్లేషించడానికి స్కానర్‌పై క్లిక్ చేయండి!',

    // Scanner
    positionMedicine: 'మందుల లేబుల్‌ను ఇక్కడ ఉంచండి',
    captureAnalyze: 'క్యాప్చర్ & విశ్లేషించండి',
    uploadFile: 'ఫైల్ అప్‌లోడ్ చేయండి',
    switchCam: 'కెమెరా మార్చండి',
    retakeScan: 'మళ్లీ స్కాన్ చేయండి',
    analyzing: 'AI విజన్‌తో మందుల ప్యాకేజింగ్ విశ్లేషించబడుతోంది...',
    analyzingDesc: 'టెక్స్ట్, క్రియాశీల పదార్థాలు, మోతాదు గుర్తులు మరియు రక్షణ వివరాలను చదువుతోంది',
    flashcards: 'ఫ్లాష్ కార్డ్‌లు',
    singleColumn: 'సింగిల్ జాబితా',
    showAllCards: 'అన్ని కార్డ్‌లు చూపించు',
    carouselView: 'ఫ్లాష్ కార్డ్ కరౌసెల్',
    previousCard: 'మునుపటి కార్డ్',
    nextCard: 'తదుపరి కార్డ్',
    cardXofY: 'కార్డ్ {x} / {y}',
    primaryUse: 'ప్రధాన ఉపయోగాలు & లక్షణాలు',
    activeIngredients: 'క్రియాశీల పదార్థాలు',
    dosageInstructions: 'మోతాదు సూచనలు',
    warnings: 'ముఖ్యమైన హెచ్చరికలు & జాగ్రత్తలు',
    sideEffects: 'దుష్ప్రభావాలు (Side Effects)',
    ncbiRecord: 'NCBI / NIH పబ్‌కెమ్ రికార్డ్',
    aiPharmacist: 'AI ఫార్మాసిస్ట్ Q&A సహాయకుడు',
    askPharmacist: 'ఈ మందుల గురించి అడగండి...',
    askBtn: 'అడగండి',
    disclaimer: '* గమనిక: ఫార్మావిజన్ AI ఒక సహాయక సాధనం. ఎల్లప్పుడూ వైద్యులు లేదా ఫార్మాసిస్ట్‌తో వివరాలను సరిచూసుకోండి.',

    // Cabinet Page
    cabinetHeader: 'నా మెడిసిన్ క్యాబినెట్',
    cabinetSubtitle: 'మీ మందులన్నీ వ్యాధుల వారీగా వర్గీకరించబడి వేగంగా వెతుక్కోవడానికి సిద్ధంగా ఉన్నాయి.',
    totalCabinetMeds: 'క్యాబినెట్‌లోని మొత్తం మందులు',
    activeDiseaseCats: 'సక్రియ వ్యాధి అరలు',
    orgStatus: 'వర్గీకరణ స్థితి',
    allSorted: '100% క్రమబద్ధం',
    aiTaxonomy: 'AI క్లినికల్ టాక్సానమీ ఇంజిన్',
    searchPlaceholder: 'మందు పేరు, పదార్థం లేదా వ్యాధి పేరుతో వెతకండి…',
    allDiseases: 'అన్ని వ్యాధులు',
    medicinesCount: '{count} మందులు',
    addedOn: '{date}న జోడించబడింది',
    viewDetails: 'వివరాలు చూడండి',
    emptyCabinet: 'మీ మెడిసిన్ క్యాబినెట్ ఖాళీగా ఉంది',
    emptyCabinetDesc: 'క్యాబినెట్‌లో చేర్చడానికి మందుల ప్యాకెట్‌ను స్కాన్ చేయండి లేదా డాక్టర్ చీటీని అప్‌లోడ్ చేయండి.',
    scanFirstMed: 'మొదటి మందును స్కాన్ చేయండి',

    // Reports & Rx Page
    reportsHeader: 'రిపోర్ట్‌లు & ప్రిస్క్రిప్షన్ ఇంటెలిజెన్స్',
    reportsSubtitle: '360° డ్యూయల్ కన్సల్టేషన్ ఆడిట్ చేయండి, 1-0-1 మోతాదులను డిజిటైజ్ చేయండి లేదా ల్యాబ్ రిపోర్టులను విశ్లేషించండి.',
    dualAuditTab: '⚡ డ్యూయల్ ఆడిట్ (ల్యాబ్ + చీటీ)',
    rxDigitizerTab: 'ప్రిస్క్రిప్షన్ డిజిటైజర్',
    labReportTab: 'ల్యాబ్ రిపోర్ట్ ఎనలైజర్',
    uploadBothDocs: 'రెండు వైద్య పత్రాలను అప్‌లోడ్ చేయండి',
    dualAuditDesc: 'డాక్టర్ రాసిన మందులు మీ అసాధారణ ల్యాబ్ రిపోర్టులకు సరిపోతాయా మరియు అవయవ భద్రతను AI తనిఖీ చేస్తుంది.',
    doc1Lab: 'పత్రం 1: బ్లడ్ / ల్యాబ్ రిపోర్ట్ (PDF / ఫోటో)',
    clickUploadLab: 'ల్యాబ్ రిపోర్ట్ అప్‌లోడ్ చేయడానికి క్లిక్ చేయండి',
    doc2Rx: 'పత్రం 2: డాక్టర్ ప్రిస్క్రిప్షన్ / చీటీ (PDF / ఫోటో)',
    clickUploadRx: 'డాక్టర్ చీటీ అప్‌లోడ్ చేయడానికి క్లిక్ చేయండి',
    runDualAuditBtn: '360° డ్యూయల్ ఆడిట్ ప్రారంభించండి',
    uploadRxTitle: 'డాక్టర్ ప్రిస్క్రిప్షన్ (Rx) అప్‌లోడ్ చేయండి',
    rxUploadDesc: 'చేతిరాత చీటీలు, క్లినిక్ స్లిప్‌లు మరియు ఇ-ప్రిస్క్రిప్షన్‌లు (PDF, PNG, JPG)',
    digitizeRxBtn: 'చీటీ నుండి మందులు & మోతాదులు తీయండి',
    uploadLabTitle: 'బ్లడ్ / ల్యాబ్ రిపోర్ట్ అప్‌లోడ్ చేయండి',
    labUploadDesc: 'రక్త పరీక్షలు, లిపిడ్ ప్రొఫైల్, మెటబాలిక్ రిపోర్ట్‌లు (10MB వరకు)',
    analyzeLabBtn: 'రిపోర్ట్‌ను విశ్లేషించి క్యాబినెట్‌తో సరిచూడండి',

    // Flashcard Sections (Shared)
    reportSummary: 'రిపోర్ట్ సారాంశం',
    labBiomarkers: 'ల్యాబ్ బయోమార్కర్లు',
    cabinetCrossCheck: 'క్యాబినెట్ సరిచూడటం',
    targetedExercises: 'లక్ష్య వ్యాయామాలు',
    dietaryGuidance: 'ఆహార మార్గదర్శకాలు',
    rxOverview: 'ప్రిస్క్రిప్షన్ సారాంశం',
    prescribedDrugs: 'సూచించిన మందులు',
    drugSafetyAlerts: 'మందుల భద్రత & పరస్పర చర్యలు',
    clinicalIndications: 'వైద్య ఉపయోగాలు',
    doctorAdvice: 'డాక్టర్ సలహా',
    auditScorecard: '360° ఆడిట్ స్కోర్‌కార్డ్',
    organSafety: 'అవయవ రక్షణ హెచ్చరికలు',
    treatmentMatrix: 'చికిత్స అమరిక మాత్రిక',
    unaddressedGaps: 'గుర్తించబడని లోపాలు',
    lifestyleCoRx: 'జీవనశైలి & ఆహార సలహాలు',

    // Timing & Schedule
    morning: 'ఉదయం',
    afternoon: 'మధ్యాహ్నం',
    night: 'రాత్రి',
    duration: 'వ్యవధి',
    timing: 'సమయం',
    saveToCabinet: 'క్యాబినెట్‌లో భద్రపరచండి ({count})',
    selectedOf: 'ఎంపికచేసినవి: {x} / {y}',

    // AI Health Assistant & Companion
    assistant: 'AI ఆరోగ్య సహాయకుడు',
    assistantSubtitle: 'మీ మందుల క్యాబినెట్ & అలెర్జీల పూర్తి సమాచారంతో వ్యక్తిగత ఆరోగ్య సహాయకుడు.',
    activeMedsCount: '{count} మందులు సక్రియం',
    allergensCount: '{count} అలెర్జీలు రక్షణలో',
    conditionsCount: '{count} ఆరోగ్య పరిస్థితులు',
    askAssistantPlaceholder: 'మీ మందులు, పరస్పర చర్యలు, దుష్ప్రభావాలు లేదా ఆహార నియమాల గురించి ఏదైనా అడగండి…',
    quickPromptsTitle: 'సూచించిన ప్రశ్నలు',
    promptInteractions: '🔍 నా అన్ని మందుల మధ్య పరస్పర చర్యలను (interactions) తనిఖీ చేయండి',
    promptSchedule: '⏰ నా రోజువారీ మందుల షెడ్యూల్ & ఆహార సమయాలు ఏమిటి?',
    promptAllergies: '🛡️ నా నమోదు చేయబడిన అలెర్జీలతో నా ప్రస్తుత మందులన్నీ సురక్షితమేనా?',
    promptFoods: '🍏 నా మందులతో నేను ఏ ఆహారాలు, రసాలు లేదా సప్లిమెంట్లను నివారించాలి?',
    promptMissedDose: '❓ నేను షెడ్యూల్ చేసిన మోతాదును మిస్ అయితే ఏమి చేయాలి?',
    clearChat: 'చర్చను క్లియర్ చేయండి',
    exportTranscript: 'కన్సల్టేషన్ డౌన్‌లోడ్ చేయండి',
    listening: 'వింటున్నాను... మాట్లాడండి',
    voiceInput: 'వాయిస్ ఇన్‌పుట్ (మైక్)',
    readAloud: 'చదివి వినిపించండి',
    stopAudio: 'ఆడియో ఆపండి',
    openAssistant: 'AI ఆరోగ్య సహాయకుడిని తెరవండి'
  }
};

export const LanguageProvider = ({ children }) => {
  const [lang, setLang] = useState(() => {
    return localStorage.getItem('pharmavision_lang') || 'en';
  });

  const changeLanguage = (newLang) => {
    if (translations[newLang]) {
      setLang(newLang);
      localStorage.setItem('pharmavision_lang', newLang);
      // Dispatch storage event so other tabs and components update seamlessly
      window.dispatchEvent(new Event('languageChange'));
    }
  };

  const t = (key, params = {}) => {
    let str = translations[lang]?.[key] || translations['en']?.[key] || key;
    if (typeof str === 'string') {
      Object.keys(params).forEach(p => {
        str = str.replace(new RegExp(`\\{${p}\\}`, 'g'), params[p]);
      });
    }
    return str;
  };

  return (
    <LanguageContext.Provider value={{ lang, changeLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
