import React, { createContext, useContext, useState, useEffect } from 'react';

const LanguageContext = createContext();

export const translations = {
  en: {
    // App & Nav
    appName: 'PharmaVision AI',
    tagline: 'Medication Safety & Health Assistant',
    menu: 'Menu',
    home: 'Home',
    assistant: 'AI Pharmacist',
    assistantSubtitle: 'Ask medication questions, check food & drug interactions, and get safety advice',
    scanner: 'Medicine Scanner',
    reportsRx: 'Reports & Prescriptions',
    cabinet: 'My Medicine Cabinet',
    memoryCare: 'Daily Care & Memory',
    caregiver: 'Caregiver Portal',
    voiceTherapy: 'Voice Check-in Room',
    history: 'History & Logs',
    profile: 'Profile & Allergies',
    sectionClinical: 'Prescriptions & Scans',
    sectionCognitive: 'Daily Care & Routines',
    sectionSupport: 'Support & Records',
    medicationSafety: 'Medication Safety & Prescriptions',
    cognitiveVitality: 'Daily Routine & Check-ins',
    nextScheduledDose: 'Next Medication Dose',
    testAlarm: 'Test Alarm Sound',
    dailyOrientationQuiz: 'Daily 2-Minute Check-in',
    voiceCalmCheckin: 'Calm Voice Check-in',
    caregiverOverview: 'Family & Caregiver Overview',
    logout: 'Sign Out',
    signIn: 'Sign In',
    signUp: 'Sign Up',
    register: 'Create Account',
    email: 'Email Address',
    password: 'Password',
    fullName: 'Full Name',
    alreadyAccount: 'Already have an account?',
    noAccount: "Don't have an account?",
    selectLanguage: 'Language',
    listenAudio: 'Listen (Audio)',
    speaking: 'Reading aloud...',

    // Dashboard
    goodMorning: 'Good morning',
    goodAfternoon: 'Good afternoon',
    goodEvening: 'Good evening',
    dashboardSubtitle: "Here is your medication schedule, safety alerts, and daily routine overview.",
    totalScans: 'Total Medicines Scanned',
    allTimeScans: 'Medicines verified and saved',
    lastScanDate: 'Last Scan Date',
    noRecentScans: 'No recent scans',
    latestDrug: 'Latest Medicine',
    verifiedAI: 'Verified by Scanner',
    scanNewMedicine: 'Scan a Medicine',
    scanNewDesc: 'Point your camera at any medicine packaging to check dosage, indications, and safety warnings',
    openScanner: 'Open Medicine Scanner',
    myCabinetTitle: 'My Medicine Cabinet',
    myCabinetDesc: 'View your saved medications organized by condition and daily schedule',
    openCabinet: 'Open Medicine Cabinet',
    reportsRxTitle: 'Prescriptions & Lab Reports',
    reportsRxDesc: 'Read doctor prescriptions (Morning/Afternoon/Night) or compare with your blood lab reports',
    openReports: 'Open Reports & Prescriptions',
    recentScans: 'Recent Medicines',
    viewAllHistory: 'View All History',
    noScansYet: 'No medicines scanned yet. Click Medicine Scanner to analyze your first medication!',
    openAssistant: 'Ask AI Pharmacist',

    // Scanner
    positionMedicine: 'Position Medicine Label in Frame',
    captureAnalyze: 'Scan & Check Medicine',
    uploadFile: 'Upload Photo or PDF',
    switchCam: 'Switch Camera',
    retakeScan: 'Scan Another Medicine',
    analyzing: 'Reading Medicine Details...',
    analyzingDesc: 'Identifying active ingredients, dosage instructions, and critical safety warnings',
    flashcards: 'Flashcards',
    singleColumn: 'Single Column',
    showAllCards: 'Show All Cards',
    carouselView: 'Card Carousel',
    previousCard: 'Previous Card',
    nextCard: 'Next Card',
    cardXofY: 'Card {x} of {y}',
    primaryUse: 'What is this medicine for?',
    activeIngredients: 'Active Ingredients',
    dosageInstructions: 'How to Take (Dosage)',
    warnings: 'Important Warnings & Precautions',
    sideEffects: 'Common Side Effects',
    ncbiRecord: 'Official Medical Record (NIH/PubChem)',
    aiPharmacist: 'AI Pharmacist Assistant',
    askPharmacist: 'Ask a question about this medicine...',
    askBtn: 'Ask',
    disclaimer: '* Notice: PharmaVision AI is an assistive guide. Always consult your doctor or pharmacist before taking or changing medication.',

    // Reports & Prescriptions (ReportAnalyzer.jsx)
    reportsHeader: 'Prescription & Lab Report Checker',
    reportsSubtitle: 'Digitize doctor prescriptions (1-0-1 schedule) or compare your blood test results with your medications',
    reportsHeaderTitle: 'Prescriptions & Blood Lab Reports',
    reportsHeaderDesc: 'Extract medications, daily dosage times, and blood test markers from photos or PDFs',
    dualAuditTab: 'Compare Lab & Prescription',
    rxDigitizerTab: 'Read Doctor Prescription',
    labReportTab: 'Analyze Blood Lab Report',
    tabPrescription: 'Doctor Prescription (1-0-1)',
    tabLabReport: 'Blood Test / Lab Report',
    tabDualAudit: 'Compare Lab & Prescription',
    uploadBothDocs: 'Upload Both Documents to Check Safety',
    dualAuditDesc: 'Compare your blood test results with your doctor prescription to check for drug-disease conflicts or organ stress',
    doc1Lab: 'Document 1: Blood Test / Lab Report (Photo or PDF)',
    clickUploadLab: 'Click or drop your Lab Report here',
    doc2Rx: 'Document 2: Doctor Prescription (Photo or PDF)',
    clickUploadRx: 'Click or drop your Doctor Prescription here',
    runDualAuditBtn: 'Check Prescription Against Lab Report',
    uploadRxTitle: 'Upload Doctor Prescription',
    rxUploadDesc: 'Read medication names, strengths, timings (Morning / Afternoon / Night), and food instructions',
    digitizeRxBtn: 'Read & Save Prescription',
    uploadLabTitle: 'Upload Blood Lab Report',
    labUploadDesc: 'Check for out-of-range values, key health markers, and diet/lifestyle recommendations',
    analyzeLabBtn: 'Analyze Lab Report',

    // Cabinet (Cabinet.jsx)
    cabinetHeader: 'My Medicine Cabinet',
    cabinetSubtitle: 'Your saved medications organized by condition and daily schedule',
    cabinetHeaderTitle: 'My Medicine Cabinet',
    cabinetHeaderDesc: 'Keep track of all your medications, refill times, and alarm reminders',
    totalCabinetMeds: 'Total Medicines',
    activeDiseaseCats: 'Condition Categories',
    allDiseases: 'All Categories',
    orgStatus: 'Organization',
    allSorted: 'All Organized',
    aiTaxonomy: 'Categories',
    allShelves: 'All Categories',
    scheduleView: 'Daily Schedule',
    searchMedicine: 'Search by medicine name or ingredient...',
    searchPlaceholder: 'Search medicines by brand, ingredient, or condition…',
    emptyCabinet: 'Your Medicine Cabinet is Empty',
    emptyCabinetDesc: 'Scan a medicine or upload a prescription to automatically add it to your cabinet.',
    scanFirstMed: 'Scan Your First Medicine',
    viewDetails: 'View Details',
    exportPdf: 'Save as PDF',
    alarmSettings: 'Reminder Times',
    morning: 'Morning',
    afternoon: 'Afternoon',
    night: 'Night',

    // Memory Care & Cognitive
    memoryCareTitle: 'Daily Care & Memory Exercises',
    memoryCareSubtitle: 'Gentle daily check-ins, family photo recall, and mental sharpness exercises',
    startMemoryMatch: 'Play Memory Match Game',
    dailyQuiz: 'Daily 2-Minute Quiz',
    cognitiveIndex: 'Wellness Score',
    recallLatency: 'Average Response Time',
    caregiverTelemetry: 'Family Summary',
    viewDashboard: 'Go to Dashboard →',
    familyVault: 'Family Memory Album',
    addMemoryQuestion: 'Add a Family Memory Question',

    // Caregiver
    caregiverTitle: 'Family & Caregiver Portal',
    caregiverSubtitle: 'View daily medication routine adherence and wellness check-in summaries',
    cloudSynced: 'Synced to Cloud',
    offlineMode: 'Offline Mode',
    adherenceRate: 'Medication Adherence',
    syncNow: 'Sync Data',
    primaryCaregiver: 'Primary Caregiver',
    routineTelemetry: 'Routine Summary',
    emergencyProtocol: 'Emergency Contact Info',

    // Assistant
    connectedCabinet: '{count} Medicines in your Cabinet',
    allergenShieldActive: 'Allergy Shield: {count} recorded allergies',
    conditionsCount: '{count} Health Conditions Tracked',
    askAssistantPlaceholder: 'Ask anything about your medicines, food interactions, side effects, or meal timing…',
    quickPromptsTitle: 'Common Questions You Can Ask',
    promptInteractions: 'Do any of my cabinet medicines interact with each other?',
    promptSchedule: 'What is my daily medicine routine and meal timing?',
    promptAllergies: 'Are my current medicines safe with my recorded allergies?',
    promptFoods: 'Which foods, juices, or vitamins should I avoid with my pills?',
    promptMissedDose: 'What should I do if I forget or miss a dose?',
    clearChat: 'Clear Conversation',
    exportTranscript: 'Download Conversation',
    listening: 'Listening… please speak now',
    voiceInput: 'Speak into Microphone',
    readAloud: 'Read Aloud',
    stopAudio: 'Stop Audio'
  },

  hi: {
    // App & Nav
    appName: 'फार्माविज़न एआई',
    tagline: 'दवा सुरक्षा और स्वास्थ्य सहायक',
    menu: 'मेनू',
    home: 'होम',
    assistant: 'एआई फार्मासिस्ट',
    assistantSubtitle: 'दवाओं की सुरक्षा, भोजन के साथ नियम और दुष्प्रभावों के बारे में पूछें',
    scanner: 'दवा स्कैनर',
    reportsRx: 'रिपोर्ट और पर्ची',
    cabinet: 'मेरी दवा अलमारी',
    memoryCare: 'दैनिक देखभाल और याददाश्त',
    caregiver: 'परिवार और देखभालकर्ता',
    voiceTherapy: 'आवाज चेक-इन कक्ष',
    history: 'इतिहास',
    profile: 'प्रोफ़ाइल और एलर्जी',
    sectionClinical: 'पर्ची और दवा स्कैन',
    sectionCognitive: 'दैनिक दिनचर्या और देखभाल',
    sectionSupport: 'सहायता और रिकॉर्ड',
    medicationSafety: 'दवा सुरक्षा और अलार्म',
    cognitiveVitality: 'दैनिक दिनचर्या और चेक-इन',
    nextScheduledDose: 'अगली दवा का समय',
    testAlarm: 'अलार्म की आवाज़ जांचें',
    dailyOrientationQuiz: 'दैनिक 2-मिनट की मानसिक जांच',
    voiceCalmCheckin: 'आरामदायक आवाज चेक-इन',
    caregiverOverview: 'परिवार और देखभाल सारांश',
    logout: 'लॉगआउट',
    signIn: 'साइन इन करें',
    signUp: 'साइन अप करें',
    register: 'पंजीकरण करें',
    email: 'ईमेल पता',
    password: 'पासवर्ड',
    fullName: 'पूरा नाम',
    alreadyAccount: 'क्या आपके पास पहले से एक खाता है?',
    noAccount: 'खाता नहीं है?',
    selectLanguage: 'भाषा',
    listenAudio: 'ऑडियो सुनें',
    speaking: 'पढ़कर सुनाया जा रहा है...',

    // Dashboard
    goodMorning: 'शुभ प्रभात',
    goodAfternoon: 'शुभ दोपहर',
    goodEvening: 'शुभ संध्या',
    dashboardSubtitle: 'आपकी दवाओं का शेड्यूल, सुरक्षा चेतावनी और दैनिक स्वास्थ्य सारांश।',
    totalScans: 'कुल जांची गई दवाएं',
    allTimeScans: 'सत्यापित और सुरक्षित दवाएं',
    lastScanDate: 'अंतिम स्कैन तिथि',
    noRecentScans: 'कोई हालिया स्कैन नहीं',
    latestDrug: 'नवीनतम दवा',
    verifiedAI: 'स्कैनर द्वारा सत्यापित',
    scanNewMedicine: 'नई दवा स्कैन करें',
    scanNewDesc: 'खुराक, उपयोग और सुरक्षा निर्देशों के लिए दवा के डिब्बे या पत्ते पर कैमरा रखें',
    openScanner: 'स्कैनर खोलें',
    myCabinetTitle: 'मेरी दवा अलमारी',
    myCabinetDesc: 'अपनी सभी दवाओं को बीमारी और समय के अनुसार व्यवस्थित देखें',
    openCabinet: 'दवा अलमारी खोलें',
    reportsRxTitle: 'पर्ची और लैब रिपोर्ट',
    reportsRxDesc: 'डॉक्टर की पर्ची (सुबह/दोपहर/रात) पढ़ें या खून की जांच रिपोर्ट से मिलान करें',
    openReports: 'रिपोर्ट्स और पर्ची खोलें',
    recentScans: 'हाल की दवाएं',
    viewAllHistory: 'पूरा इतिहास देखें',
    noScansYet: 'अभी तक कोई दवा स्कैन नहीं हुई है। अपनी पहली दवा का विश्लेषण करने के लिए स्कैनर पर क्लिक करें!',
    openAssistant: 'एआई फार्मासिस्ट से पूछें',

    // Scanner
    positionMedicine: 'दवा के लेबल को यहाँ फ्रेम में रखें',
    captureAnalyze: 'स्कैन करें और जांचें',
    uploadFile: 'फ़ोटो या पीडीएफ अपलोड करें',
    switchCam: 'कैमरा बदलें',
    retakeScan: 'दूसरी दवा स्कैन करें',
    analyzing: 'दवा का विवरण पढ़ा जा रहा है...',
    analyzingDesc: 'सक्रिय घटक, खुराक के निर्देश और महत्वपूर्ण चेतावनियां जांची जा रही हैं',
    flashcards: 'फ़्लैशकार्ड्स',
    singleColumn: 'एकल कॉलम',
    showAllCards: 'सभी कार्ड दिखाएं',
    carouselView: 'कार्ड स्लाइडर',
    previousCard: 'पिछला कार्ड',
    nextCard: 'अगला कार्ड',
    cardXofY: 'कार्ड {x} का {y}',
    primaryUse: 'यह दवा किस काम आती है?',
    activeIngredients: 'सक्रिय घटक (साल्ट)',
    dosageInstructions: 'दवा लेने का सही तरीका (खुराक)',
    warnings: 'महत्वपूर्ण चेतावनियां और सावधानियां',
    sideEffects: 'सामान्य दुष्प्रभाव',
    ncbiRecord: 'एनसीबीआई / पबकेम रिकॉर्ड',
    aiPharmacist: 'एआई फार्मासिस्ट सहायक',
    askPharmacist: 'इस दवा के बारे में पूछें...',
    askBtn: 'पूछें',
    disclaimer: '* सूचना: फार्माविज़न एआई एक सहायक उपकरण है। दवा लेने से पहले हमेशा डॉक्टर या फार्मासिस्ट से पुष्टि करें।',

    // Reports & Prescriptions (ReportAnalyzer.jsx)
    reportsHeader: 'पर्ची और लैब रिपोर्ट की जांच',
    reportsSubtitle: 'डॉक्टर की पर्ची (सुबह-दोपहर-रात खुराक) पढ़ें या लैब ब्लड रिपोर्ट के साथ मिलान करें',
    reportsHeaderTitle: 'पर्ची और ब्लड लैब रिपोर्ट',
    reportsHeaderDesc: 'कैमरे या पीडीएफ से दवाएं, समय और रक्त परीक्षण के परिणाम निकालें',
    dualAuditTab: 'लैब और पर्ची का मिलान',
    rxDigitizerTab: 'डॉक्टर की पर्ची पढ़ें',
    labReportTab: 'ब्लड लैब रिपोर्ट विश्लेषक',
    tabPrescription: 'डॉक्टर की पर्ची (1-0-1)',
    tabLabReport: 'ब्लड टेस्ट लैब रिपोर्ट',
    tabDualAudit: 'लैब और पर्ची का मिलान',
    uploadBothDocs: 'लैब रिपोर्ट और डॉक्टर की पर्ची अपलोड करें',
    dualAuditDesc: 'दवाओं और रक्त परीक्षण परिणामों का मिलान करके परस्पर विरोध और कमियों की जाँच करें',
    doc1Lab: 'दस्तावेज़ 1: लैब टेस्ट रिपोर्ट (फ़ोटो या पीडीएफ)',
    clickUploadLab: 'अपनी लैब रिपोर्ट यहाँ अपलोड करें',
    doc2Rx: 'दस्तावेज़ 2: डॉक्टर की पर्ची (फ़ोटो या पीडीएफ)',
    clickUploadRx: 'अपनी डॉक्टर की पर्ची यहाँ अपलोड करें',
    runDualAuditBtn: 'पर्ची और लैब रिपोर्ट की तुलना करें',
    uploadRxTitle: 'डॉक्टर की पर्ची अपलोड करें',
    rxUploadDesc: 'दवा का नाम, खुराक (सुबह/दोपहर/रात) और खाने के निर्देश निकालें',
    digitizeRxBtn: 'पर्ची पढ़ें और सहेजें',
    uploadLabTitle: 'ब्लड लैब रिपोर्ट अपलोड करें',
    labUploadDesc: 'असामान्य स्वास्थ्य संकेतकों और खान-पान के सुझावों की जांच करें',
    analyzeLabBtn: 'लैब रिपोर्ट का विश्लेषण करें',

    // Cabinet (Cabinet.jsx)
    cabinetHeader: 'मेरी दवा अलमारी',
    cabinetSubtitle: 'आपकी दवाएं बीमारी और दैनिक समय के अनुसार व्यवस्थित हैं',
    cabinetHeaderTitle: 'मेरी दवा अलमारी',
    cabinetHeaderDesc: 'अपनी सभी दवाओं, अलार्म समय और शेड्यूल पर नज़र रखें',
    totalCabinetMeds: 'कुल दवाएं',
    activeDiseaseCats: 'बीमारी की श्रेणियां',
    allDiseases: 'सभी श्रेणियां',
    orgStatus: 'व्यवस्था',
    allSorted: 'व्यवस्थित',
    aiTaxonomy: 'श्रेणियां',
    allShelves: 'सभी श्रेणियां',
    scheduleView: 'दैनिक समय सारणी',
    searchMedicine: 'दवा या साल्ट का नाम खोजें...',
    searchPlaceholder: 'दवा के नाम, साल्ट या बीमारी से खोजें…',
    emptyCabinet: 'आपकी दवा अलमारी खाली है',
    emptyCabinetDesc: 'अलमारी में जोड़ने के लिए कोई दवा स्कैन करें या पर्ची अपलोड करें।',
    scanFirstMed: 'अपनी पहली दवा स्कैन करें',
    viewDetails: 'विवरण देखें',
    exportPdf: 'पीडीएफ डाउनलोड करें',
    alarmSettings: 'अलार्म का समय',
    morning: 'सुबह',
    afternoon: 'दोपहर',
    night: 'रात',

    // Memory Care & Cognitive
    memoryCareTitle: 'दैनिक देखभाल और याददाश्त',
    memoryCareSubtitle: 'दैनिक चेक-इन, पारिवारिक फोटो यादें और मानसिक तंदुरुस्ती',
    startMemoryMatch: 'मेमोरी मैच खेल खेलें',
    dailyQuiz: 'दैनिक 2-मिनट प्रश्नोत्तरी',
    cognitiveIndex: 'स्वास्थ्य स्कोर',
    recallLatency: 'औसत उत्तर समय',
    caregiverTelemetry: 'पारिवारिक सारांश',
    viewDashboard: 'डैशबोर्ड पर जाएं →',
    familyVault: 'पारिवारिक फोटो एल्बम',
    addMemoryQuestion: 'पारिवारिक प्रश्न जोड़ें',

    // Caregiver
    caregiverTitle: 'परिवार और देखभालकर्ता पोर्टल',
    caregiverSubtitle: 'दैनिक दवा लेने के नियम और स्वास्थ्य सारांश देखें',
    cloudSynced: 'क्लाउड सिंक हुआ',
    offlineMode: 'ऑफलाइन मोड',
    adherenceRate: 'दवा लेने की नियमितता',
    syncNow: 'डेटा सिंक करें',
    primaryCaregiver: 'मुख्य देखभालकर्ता',
    routineTelemetry: 'दैनिक सारांश',
    emergencyProtocol: 'आपातकालीन संपर्क जानकारी',

    // Assistant
    connectedCabinet: 'अलमारी में {count} दवाएं सुरक्षित हैं',
    allergenShieldActive: 'एलर्जी सुरक्षा: {count} दर्ज की गई एलर्जी',
    conditionsCount: '{count} स्वास्थ्य स्थितियां ट्रैक की गईं',
    askAssistantPlaceholder: 'अपनी दवाओं, खाने के साथ नियम, दुष्प्रभावों या समय के बारे में कुछ भी पूछें…',
    quickPromptsTitle: 'अक्सर पूछे जाने वाले प्रश्न',
    promptInteractions: 'क्या मेरी अलमारी की कोई दवा आपस में नुकसान करती है?',
    promptSchedule: 'मेरी दवाओं का सही समय और खाने के नियम क्या हैं?',
    promptAllergies: 'क्या ये दवाएं मेरी एलर्जी के हिसाब से सुरक्षित हैं?',
    promptFoods: 'इन दवाओं के साथ किन खाद्य पदार्थों या फलों से बचना चाहिए?',
    promptMissedDose: 'यदि मैं दवा लेना भूल जाऊं तो मुझे क्या करना चाहिए?',
    clearChat: 'बातचीत साफ़ करें',
    exportTranscript: 'परामर्श डाउनलोड करें',
    listening: 'सुन रहे हैं… कृपया बोलें',
    voiceInput: 'माइक से बोलें',
    readAloud: 'बोलकर सुनाएं',
    stopAudio: 'आवाज रोकें'
  },

  te: {
    appName: 'ఫార్మావిజన్ AI',
    tagline: 'ఔషధ భద్రత మరియు ఆరోగ్య సహాయకుడు',
    menu: 'మెనూ',
    home: 'హోమ్',
    assistant: 'AI ఫార్మసిస్ట్',
    assistantSubtitle: 'మందులు, మోతాదు మరియు దుష్ప్రభావాల గురించి అడగండి',
    scanner: 'మందుల స్కానర్',
    reportsRx: 'నివేదికలు & ప్రిస్క్రిప్షన్',
    cabinet: 'నా మందుల అల్మారా',
    memoryCare: 'రోజువారీ సంరక్షణ & జ్ఞాపకశక్తి',
    caregiver: 'కుటుంబ పోర్టల్',
    voiceTherapy: 'వాయిస్ రూమ్',
    history: 'చరిత్ర',
    profile: 'ప్రొఫైల్',
    sectionClinical: 'ప్రిస్క్రిప్షన్ & స్కానింగ్',
    sectionCognitive: 'రోజువారీ దినచర్య & సంరక్షణ',
    sectionSupport: 'సహాయం & రికార్డులు',
    medicationSafety: 'మందుల భద్రత & అలారాలు',
    cognitiveVitality: 'రోజువారీ దినచర్య',
    nextScheduledDose: 'తదుపరి మందుల సమయం',
    testAlarm: 'అలారం ధ్వనిని పరీక్షించండి',
    dailyOrientationQuiz: 'రోజువారీ 2-నిమిషాల క్విజ్',
    voiceCalmCheckin: 'ప్రశాంతమైన వాయిస్ చెక్-ఇన్',
    caregiverOverview: 'కుటుంబ సంరక్షణ సారాంశం',
    logout: 'లాగౌట్',
    signIn: 'సైన్ ఇన్',
    signUp: 'సైన్ అప్',
    register: 'నమోదు చేయండి',
    email: 'ఈమెయిల్ చిరునామా',
    password: 'పాస్‌వర్డ్',
    fullName: 'పూర్తి పేరు',
    selectLanguage: 'భాష',
    goodMorning: 'శుభోదయం',
    goodAfternoon: 'శుభ మధ్యాహ్నం',
    goodEvening: 'శుభ సాయంత్రం',
    dashboardSubtitle: 'మీ మందుల షెడ్యూల్ మరియు ఆరోగ్య సమాచారం ఇక్కడ ఉంది.',
    totalScans: 'మొత్తం స్కాన్ చేసిన మందులు',
    allTimeScans: 'ధృవీకరించబడిన మందులు',
    scanNewMedicine: 'కొత్త మందును స్కాన్ చేయండి',
    openScanner: 'స్కానర్ తెరవండి',
    myCabinetTitle: 'నా మందుల అల్మారా',
    openCabinet: 'అల్మారా తెరవండి',
    reportsRxTitle: 'నివేదికలు మరియు ప్రిస్క్రిప్షన్లు',
    openReports: 'నివేదికలు తెరవండి',
    recentScans: 'ఇటీవలి మందులు',
    viewAllHistory: 'పూర్తి చరిత్ర చూడండి',
    primaryUse: 'ఈ మందు దేనికి ఉపయోగపడుతుంది?',
    activeIngredients: 'క్రియాశీల పదార్థాలు',
    dosageInstructions: 'వాడే విధానం (మోతాదు)',
    warnings: 'ముఖ్యమైన జాగ్రత్తలు',
    sideEffects: 'సాధారణ దుష్ప్రభావాలు',
    reportsHeader: 'ప్రిస్క్రిప్షన్ & ల్యాబ్ నివేదిక పరిశీలన',
    reportsSubtitle: 'ప్రిస్క్రిప్షన్ చదవండి లేదా ల్యాబ్ రక్త పరీక్షతో సరిపోల్చండి',
    dualAuditTab: 'ల్యాబ్ & ప్రిస్క్రిప్షన్ సరిపోల్చండి',
    rxDigitizerTab: 'డాక్టర్ ప్రిస్క్రిప్షన్ చదవండి',
    labReportTab: 'ల్యాబ్ నివేదిక విశ్లేషణ',
    cabinetHeader: 'నా మందుల అల్మారా',
    cabinetSubtitle: 'మీ మందులు క్రమపద్ధతిలో అమర్చబడ్డాయి',
    totalCabinetMeds: 'మొత్తం మందులు'
  },

  ta: {
    appName: 'பார்மாவிஷன் AI',
    tagline: 'மருந்து பாதுகாப்பு மற்றும் சுகாதார உதவியாளர்',
    menu: 'மெனு',
    home: 'முகப்பு',
    assistant: 'AI மருந்தாளர்',
    assistantSubtitle: 'மருந்துகள், அளவு மற்றும் பக்க விளைவுகள் பற்றி கேளுங்கள்',
    scanner: 'மருந்து ஸ்கேனர்',
    reportsRx: 'அறிக்கைகள் & மருந்துச்சீட்டு',
    cabinet: 'என் மருந்து பெட்டி',
    memoryCare: 'நினைவாற்றல் மற்றும் தினசரி பராமரிப்பு',
    caregiver: 'குடும்ப பராமரிப்பாளர்',
    voiceTherapy: 'குரல் அறை',
    history: 'வரலாறு',
    profile: 'சுயவிவரம்',
    sectionClinical: 'மருந்துச்சீட்டு & ஸ்கேனர்',
    sectionCognitive: 'தினசரி வழக்கம் & நலம்',
    sectionSupport: 'உதவி & பதிவுகள்',
    medicationSafety: 'மருந்து பாதுகாப்பு & எச்சரிக்கை',
    cognitiveVitality: 'தினசரி வழக்கம்',
    nextScheduledDose: 'அடுத்த மருந்து நேரம்',
    testAlarm: 'அலாரத்தை சோதிக்கவும்',
    logout: 'வெளியேறு',
    goodMorning: 'காலை வணக்கம்',
    goodAfternoon: 'மதிய வணக்கம்',
    goodEvening: 'மாலை வணக்கம்',
    dashboardSubtitle: 'உங்கள் மருந்து அட்டவணை மற்றும் சுகாதார சுருக்கம் இங்கே உள்ளது.',
    totalScans: 'ஸ்கேன் செய்யப்பட்ட மருந்துகள்',
    scanNewMedicine: 'புதிய மருந்தை ஸ்கேன் செய்யவும்',
    openScanner: 'ஸ்கேனரை திறக்கவும்',
    myCabinetTitle: 'என் மருந்து பெட்டி',
    openCabinet: 'பெட்டியை திறக்கவும்',
    reportsRxTitle: 'அறிக்கைகள் மற்றும் மருந்துச்சீட்டுகள்',
    openReports: 'அறிக்கைகளை திறக்கவும்',
    recentScans: 'சமீபத்திய மருந்துகள்',
    primaryUse: 'இந்த மருந்து எதற்கு பயன்படுகிறது?',
    activeIngredients: 'செயலில் உள்ள கூறுகள்',
    dosageInstructions: 'மருந்து உட்கொள்ளும் முறை (அளவு)',
    warnings: 'முக்கிய எச்சரிக்கைகள்',
    sideEffects: 'பக்க விளைவுகள்',
    reportsHeader: 'மருந்துச்சீட்டு மற்றும் ஆய்வக அறிக்கை சரிபார்ப்பு',
    reportsSubtitle: 'மருத்துவர் மருந்துச்சீட்டை படிக்கவும் அல்லது இரத்த அறிக்கையுடன் ஒப்பிடவும்',
    dualAuditTab: 'ஆய்வகம் & மருந்துச்சீட்டு ஒப்பீடு',
    rxDigitizerTab: 'மருந்துச்சீட்டை படிக்கவும்',
    labReportTab: 'இரத்த அறிக்கை பகுப்பாய்வு',
    cabinetHeader: 'என் மருந்து பெட்டி',
    cabinetSubtitle: 'உங்கள் மருந்துகள் நோய்களின்படி ஒழுங்கமைக்கப்பட்டுள்ளன',
    totalCabinetMeds: 'மொத்த மருந்துகள்'
  },

  kn: {
    appName: 'ಫಾರ್ಮಾವಿಷನ್ AI',
    tagline: 'ಔಷಧ ಸುರಕ್ಷತೆ ಮತ್ತು ಆರೋಗ್ಯ ಸಹಾಯಕ',
    menu: 'ಮೆನು',
    home: 'ಮುಖಪುಟ',
    assistant: 'AI ಫಾರ್ಮಸಿಸ್ಟ್',
    scanner: 'ಔಷಧಿ ಸ್ಕ್ಯಾನರ್',
    reportsRx: 'ವರದಿಗಳು & ಪ್ರಿಸ್ಕ್ರಿಪ್ಷನ್',
    cabinet: 'ನನ್ನ ಔಷಧಿ ಕ್ಯಾಬಿನೆಟ್',
    memoryCare: 'ದೈನಂದಿನ ಕಾಳಜಿ & ನೆನಪಿನ ಶಕ್ತಿ',
    caregiver: 'ಪಾಲಕರ ಪೋರ್ಟಲ್',
    voiceTherapy: 'ಧ್ವನಿ ಕೋಣೆ',
    history: 'ಇತಿಹಾಸ',
    profile: 'ಪ್ರೊಫೈಲ್',
    sectionClinical: 'ಪ್ರಿಸ್ಕ್ರಿಪ್ಷನ್ & ಸ್ಕ್ಯಾನಿಂಗ್',
    sectionCognitive: 'ದೈನಂದಿನ ದಿನಚರಿ & ಕಾಳಜಿ',
    sectionSupport: 'ಬೆಂಬಲ & ದಾಖಲೆಗಳು',
    medicationSafety: 'ಔಷಧ ಸುರಕ್ಷತೆ & ಎಚ್ಚರಿಕೆ',
    nextScheduledDose: 'ಮುಂದಿನ ಔಷಧಿಯ ಸಮಯ',
    testAlarm: 'ಅಲಾರಾಂ ಪರೀಕ್ಷಿಸಿ',
    logout: 'ಲಾಗೌಟ್',
    goodMorning: 'ಶುಭೋದಯ',
    goodAfternoon: 'ಶುಭ ಮಧ್ಯಾಹ್ನ',
    goodEvening: 'ಶುಭ ಸಂಜೆ',
    dashboardSubtitle: 'ನಿಮ್ಮ ಔಷಧಿಗಳ ವೇಳಾಪಟ್ಟಿ ಮತ್ತು ಆರೋಗ್ಯ ಸಾರಾಂಶ ಇಲ್ಲಿದೆ.',
    totalScans: 'ಒಟ್ಟು ಸ್ಕ್ಯಾನ್ ಮಾಡಿದ ಔಷಧಿಗಳು',
    scanNewMedicine: 'ಹೊಸ ಔಷಧಿ ಸ್ಕ್ಯಾನ್ ಮಾಡಿ',
    openScanner: 'ಸ್ಕ್ಯಾನರ್ ತೆರೆಯಿರಿ',
    myCabinetTitle: 'ನನ್ನ ಔಷಧಿ ಕ್ಯಾಬಿನೆಟ್',
    openCabinet: 'ಕ್ಯಾಬಿನೆಟ್ ತೆರೆಯಿರಿ',
    reportsRxTitle: 'ವರದಿಗಳು ಮತ್ತು ಪ್ರಿಸ್ಕ್ರಿಪ್ಷನ್',
    openReports: 'ವರದಿಗಳನ್ನು ತೆರೆಯಿರಿ',
    recentScans: 'ಇತ್ತೀಚಿನ ಔಷಧಿಗಳು',
    primaryUse: 'ಈ ಔಷಧಿಯ ಉಪಯೋಗವೇನು?',
    activeIngredients: 'ಸಕ್ರಿಯ ಪದಾರ್ಥಗಳು',
    dosageInstructions: 'ತೆಗೆದುಕೊಳ್ಳುವ ಪ್ರಮಾಣ (ಡೋಸೇಜ್)',
    warnings: 'ಪ್ರಮುಖ ಎಚ್ಚರಿಕೆಗಳು',
    sideEffects: 'ಸಾಮಾನ್ಯ ಅಡ್ಡಪರಿಣಾಮಗಳು',
    reportsHeader: 'ಪ್ರಿಸ್ಕ್ರಿಪ್ಷನ್ ಮತ್ತು ಲ್ಯಾಬ್ ವರದಿ ಪರಿಶೀಲನೆ',
    reportsSubtitle: 'ಪ್ರಿಸ್ಕ್ರಿಪ್ಷನ್ ಓದಿ ಅಥವಾ ಲ್ಯಾಬ್ ರಕ್ತ ಪರೀಕ್ಷೆಯೊಂದಿಗೆ ಹೋಲಿಕೆ ಮಾಡಿ',
    dualAuditTab: 'ಲ್ಯಾಬ್ & ಪ್ರಿಸ್ಕ್ರಿಪ್ಷನ್ ಹೋಲಿಕೆ',
    rxDigitizerTab: 'ಪ್ರಿಸ್ಕ್ರಿಪ್ಷನ್ ಓದಿ',
    labReportTab: 'ಲ್ಯಾಬ್ ವರದಿ ವಿಶ್ಲೇಷಣೆ',
    cabinetHeader: 'ನನ್ನ ಔಷಧಿ ಕ್ಯಾಬಿನೆಟ್',
    cabinetSubtitle: 'ನಿಮ್ಮ ಔಷಧಿಗಳನ್ನು ವ್ಯವಸ್ಥಿತವಾಗಿ ಜೋಡಿಸಲಾಗಿದೆ',
    totalCabinetMeds: 'ಒಟ್ಟು ಔಷಧಿಗಳು'
  },

  bn: {
    appName: 'ফার্মাভিশন AI',
    tagline: 'ওষুধের সুরক্ষা ও স্বাস্থ্য সহকারী',
    menu: 'মেনু',
    home: 'হোম',
    assistant: 'AI ফার্মাসিস্ট',
    scanner: 'ওষুধ স্ক্যানার',
    reportsRx: 'রিপোর্ট ও প্রেসক্রিপশন',
    cabinet: 'আমার ওষুধের বাক্স',
    memoryCare: 'দৈনিক যত্ন ও স্মৃতিশক্তি',
    caregiver: 'কেয়ারগিভার পোর্টাল',
    voiceTherapy: 'ভয়েস রুম',
    history: 'ইতিহাস',
    profile: 'প্রোফাইল',
    sectionClinical: 'প্রেসক্রিপশন ও স্ক্যান',
    sectionCognitive: 'দৈনিক রুটিন ও যত্ন',
    sectionSupport: 'সহায়তা ও রেকর্ড',
    medicationSafety: 'ওষুধের নিরাপত্তা ও অ্যালার্ম',
    nextScheduledDose: 'পরবর্তী ওষুধের সময়',
    testAlarm: 'অ্যালার্ম পরীক্ষা করুন',
    logout: 'লগআউট',
    goodMorning: 'সুপ্রভাত',
    goodAfternoon: 'শুভ দুপুর',
    goodEvening: 'শুভ সন্ধ্যা',
    dashboardSubtitle: 'এখানে আপনার ওষুধের সময়সূচী ও স্বাস্থ্যের সারসংক্ষেপ রয়েছে।',
    totalScans: 'মোট স্ক্যান করা ওষুধ',
    scanNewMedicine: 'নতুন ওষুধ স্ক্যান করুন',
    openScanner: 'স্ক্যানার খুলুন',
    myCabinetTitle: 'আমার ওষুধের বাক্স',
    openCabinet: 'ওষুধের বাক্স খুলুন',
    reportsRxTitle: 'রিপোর্ট এবং প্রেসক্রিপশন',
    openReports: 'রিপোর্ট খুলুন',
    recentScans: 'সাম্প্রতিক ওষুধসমূহ',
    primaryUse: 'এই ওষুধটি কী কাজে লাগে?',
    activeIngredients: 'সক্রিয় উপাদান',
    dosageInstructions: 'খাওয়ার নিয়ম (ডোজ)',
    warnings: 'গুরুত্বপূর্ণ সতর্কতা',
    sideEffects: 'পার্শ্বপ্রতিক্রিয়া',
    reportsHeader: 'প্রেসক্রিপশন ও ল্যাব রিপোর্ট যাচাই',
    reportsSubtitle: 'প্রেসক্রিপশন পড়ুন বা ল্যাব রক্ত পরীক্ষার সাথে মিলিয়ে দেখুন',
    dualAuditTab: 'ল্যাব ও প্রেসক্রিপশন তুলনা',
    rxDigitizerTab: 'প্রেসক্রিপশন পড়ুন',
    labReportTab: 'ল্যাব রিপোর্ট বিশ্লেষণ',
    cabinetHeader: 'আমার ওষুধের বাক্স',
    cabinetSubtitle: 'আপনার ওষুধগুলি রোগ অনুসারে সাজানো হয়েছে',
    totalCabinetMeds: 'মোট ওষুধ'
  },

  mr: {
    appName: 'फार्माव्हिजन AI',
    tagline: 'औषध सुरक्षा आणि आरोग्य सहाय्यक',
    menu: 'मेनू',
    home: 'मुख्यपृष्ठ',
    assistant: 'AI फार्मासिस्ट',
    scanner: 'औषध स्कॅनर',
    reportsRx: 'अहवाल आणि प्रिस्क्रिप्शन',
    cabinet: 'माझी औषध पेटी',
    memoryCare: 'दैनिक काळजी आणि स्मरणशक्ती',
    caregiver: 'कुटुंब काळजीवाहक',
    voiceTherapy: 'व्हॉइस रूम',
    history: 'इतिहास',
    profile: 'प्रोफाइल',
    sectionClinical: 'प्रिस्क्रिप्शन आणि स्कॅनिंग',
    sectionCognitive: 'दैनिक दिनचर्या आणि काळजी',
    sectionSupport: 'मदत आणि नोंदी',
    medicationSafety: 'औषध सुरक्षा आणि अलार्म',
    nextScheduledDose: 'पुढील औषधाची वेळ',
    testAlarm: 'अलार्म तपासा',
    logout: 'लॉगआउट',
    goodMorning: 'शुभ सकाळ',
    goodAfternoon: 'शुभ दुपार',
    goodEvening: 'शुभ संध्याकाळ',
    dashboardSubtitle: 'येथे आपल्या औषधांचे वेळापत्रक आणि आरोग्याचा सारांश आहे.',
    totalScans: 'एकूण स्कॅन केलेली औषधे',
    scanNewMedicine: 'नवीन औषध स्कॅन करा',
    openScanner: 'स्कॅनर उघडा',
    myCabinetTitle: 'माझी औषध पेटी',
    openCabinet: 'पेटी उघडा',
    reportsRxTitle: 'अहवाल आणि प्रिस्क्रिप्शन',
    openReports: 'अहवाल उघडा',
    recentScans: 'अलीकडील औषधे',
    primaryUse: 'हे औषध कशासाठी वापरले जाते?',
    activeIngredients: 'सक्रिय घटक',
    dosageInstructions: 'घेण्याची पद्धत (डोस)',
    warnings: 'महत्त्वाच्या सूचना आणि काळजी',
    sideEffects: 'सामान्य दुष्परिणाम',
    reportsHeader: 'प्रिस्क्रिप्शन आणि लॅब अहवाल तपासणी',
    reportsSubtitle: 'प्रिस्क्रिप्शन वाचा किंवा लॅब रक्त अहवालाशी तुलना करा',
    dualAuditTab: 'लॅब आणि प्रिस्क्रिप्शन तुलना',
    rxDigitizerTab: 'प्रिस्क्रिप्शन वाचा',
    labReportTab: 'लॅब अहवाल विश्लेषण',
    cabinetHeader: 'माझी औषध पेटी',
    cabinetSubtitle: 'आपली औषधे आजारानुसार व्यवस्थित ठेवली आहेत',
    totalCabinetMeds: 'एकूण औषधे'
  },

  es: {
    appName: 'PharmaVision AI',
    tagline: 'Seguridad de Medicamentos y Asistente de Salud',
    menu: 'Menú',
    home: 'Inicio',
    assistant: 'Farmacéutico IA',
    assistantSubtitle: 'Consulta sobre interacciones, dosis y efectos secundarios',
    scanner: 'Escáner de Medicinas',
    reportsRx: 'Informes y Recetas',
    cabinet: 'Mi Botiquín',
    memoryCare: 'Cuidado Diario y Memoria',
    caregiver: 'Portal del Cuidador',
    voiceTherapy: 'Sala de Voz',
    history: 'Historial',
    profile: 'Perfil y Alergias',
    sectionClinical: 'Recetas y Escaneos',
    sectionCognitive: 'Rutina Diaria y Bienestar',
    sectionSupport: 'Soporte y Registros',
    medicationSafety: 'Seguridad y Recordatorios',
    nextScheduledDose: 'Próxima Dosis',
    testAlarm: 'Probar Alarma',
    logout: 'Cerrar Sesión',
    signIn: 'Iniciar Sesión',
    signUp: 'Registrarse',
    register: 'Crear Cuenta',
    goodMorning: 'Buenos días',
    goodAfternoon: 'Buenas tardes',
    goodEvening: 'Buenas noches',
    dashboardSubtitle: 'Aquí está el resumen de sus medicamentos y salud diaria.',
    totalScans: 'Medicamentos Escaneados',
    scanNewMedicine: 'Escanear Medicamento',
    scanNewDesc: 'Apunta la cámara al envase del medicamento para ver dosis y seguridad',
    openScanner: 'Abrir Escáner',
    myCabinetTitle: 'Mi Botiquín',
    openCabinet: 'Abrir Botiquín',
    reportsRxTitle: 'Informes y Recetas Médicas',
    openReports: 'Abrir Informes',
    recentScans: 'Medicamentos Recientes',
    viewAllHistory: 'Ver Todo el Historial',
    primaryUse: '¿Para qué sirve este medicamento?',
    activeIngredients: 'Ingredientes Activos',
    dosageInstructions: 'Instrucciones de Dosis',
    warnings: 'Advertencias y Precauciones',
    sideEffects: 'Posibles Efectos Secundarios',
    reportsHeader: 'Revisión de Recetas e Informes de Laboratorio',
    reportsSubtitle: 'Digitalice recetas médicas (mañana/tarde/noche) o compare con análisis de sangre',
    dualAuditTab: 'Comparar Laboratorio y Receta',
    rxDigitizerTab: 'Leer Receta Médica',
    labReportTab: 'Analizar Informe de Sangre',
    cabinetHeader: 'Mi Botiquín',
    cabinetSubtitle: 'Tus medicamentos organizados por condición y horario',
    totalCabinetMeds: 'Total Medicamentos'
  }
};

export const LanguageProvider = ({ children }) => {
  const [lang, setLang] = useState(() => {
    return localStorage.getItem('pharmavision_lang') || 'en';
  });

  useEffect(() => {
    // Keep document lang attribute in sync
    document.documentElement.lang = lang;
  }, [lang]);

  const changeLanguage = (newLang) => {
    if (translations[newLang]) {
      setLang(newLang);
      localStorage.setItem('pharmavision_lang', newLang);
      document.documentElement.lang = newLang;
      // Dispatch storage event so other tabs and components update seamlessly
      window.dispatchEvent(new Event('languageChange'));
    }
  };

  /**
   * Smart, fail-safe t function:
   * 1. Looks up key in selected language
   * 2. Falls back to English dictionary
   * 3. Falls back to provided fallback string (if passed: t('myKey', 'Default String'))
   * 4. Auto-formats camelCase keys to natural readable Title Case ("reportsSubtitle" -> "Reports Subtitle")
   * Prevents raw code identifiers from ever displaying to users.
   */
  const t = (key, fallbackOrParams = {}, params = {}) => {
    let fallback = null;
    let actualParams = params;

    if (typeof fallbackOrParams === 'string') {
      fallback = fallbackOrParams;
    } else if (typeof fallbackOrParams === 'object' && fallbackOrParams !== null) {
      actualParams = fallbackOrParams;
    }

    let str = translations[lang]?.[key] || translations['en']?.[key];

    if (!str) {
      if (fallback) {
        str = fallback;
      } else if (typeof key === 'string') {
        // Convert camelCase or snake_case key to natural words
        str = key
          .replace(/_/g, ' ')
          .replace(/([A-Z])/g, ' $1')
          .replace(/^./, s => s.toUpperCase())
          .trim();
      } else {
        str = '';
      }
    }

    if (typeof str === 'string' && actualParams) {
      Object.keys(actualParams).forEach(p => {
        str = str.replace(new RegExp(`\\{${p}\\}`, 'g'), actualParams[p]);
      });
    }
    return str;
  };

  return (
    <LanguageContext.Provider value={{ lang, changeLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
